// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package pan

import (
	"math/big"

	"github.com/palletone/go-palletone/common"
	"github.com/palletone/go-palletone/common/hexutil"
	"github.com/palletone/go-palletone/consensus/consensusconfig"
	"github.com/palletone/go-palletone/dag/coredata"
	"github.com/palletone/go-palletone/dag/dagconfig"
	"github.com/palletone/go-palletone/pan/downloader"
	"github.com/palletone/go-palletone/pan/gasprice"
)

var _ = (*configMarshaling)(nil)

func (c Config) MarshalTOML() (interface{}, error) {
	type Config struct {
		//Genesis            *core.Genesis `toml:",omitempty"`//wangjiyou
		NetworkId          uint64
		SyncMode           downloader.SyncMode
		LightServ          int  `toml:",omitempty"`
		LightPeers         int  `toml:",omitempty"`
		SkipBcVersionCheck bool `toml:"-"`
		DatabaseHandles    int  `toml:"-"`
		DatabaseCache      int
		Etherbase          common.Address `toml:",omitempty"`
		MinerThreads       int            `toml:",omitempty"`
		ExtraData          hexutil.Bytes  `toml:",omitempty"`
		GasPrice           *big.Int
		//Ethash                  ethash.Config//wangjiyou
		TxPool                  coredata.TxPoolConfig
		GPO                     gasprice.Config
		EnablePreimageRecording bool
		// DAG options
		Dag       dagconfig.Config
		Consensus consensusconfig.Config
		DocRoot   string `toml:"-"`
	}
	var enc Config
	//enc.Genesis = c.Genesis
	enc.NetworkId = c.NetworkId
	enc.SyncMode = c.SyncMode
	enc.LightServ = c.LightServ
	enc.LightPeers = c.LightPeers
	enc.SkipBcVersionCheck = c.SkipBcVersionCheck
	enc.DatabaseHandles = c.DatabaseHandles
	enc.DatabaseCache = c.DatabaseCache
	enc.Etherbase = c.Etherbase
	enc.MinerThreads = c.MinerThreads
	enc.ExtraData = c.ExtraData
	enc.GasPrice = c.GasPrice
	//enc.Ethash = c.Ethash//wangjiyou
	enc.TxPool = c.TxPool
	enc.GPO = c.GPO
	enc.EnablePreimageRecording = c.EnablePreimageRecording
	enc.Dag = c.Dag
	enc.DocRoot = c.DocRoot
	return &enc, nil
}

func (c *Config) UnmarshalTOML(unmarshal func(interface{}) error) error {
	type Config struct {
		//Genesis            *core.Genesis `toml:",omitempty"`
		NetworkId          *uint64
		SyncMode           *downloader.SyncMode
		LightServ          *int  `toml:",omitempty"`
		LightPeers         *int  `toml:",omitempty"`
		SkipBcVersionCheck *bool `toml:"-"`
		DatabaseHandles    *int  `toml:"-"`
		DatabaseCache      *int
		Etherbase          *common.Address `toml:",omitempty"`
		MinerThreads       *int            `toml:",omitempty"`
		ExtraData          *hexutil.Bytes  `toml:",omitempty"`
		GasPrice           *big.Int
		//Ethash                  *ethash.Config//wangjyiou
		TxPool                  *coredata.TxPoolConfig
		GPO                     *gasprice.Config
		EnablePreimageRecording *bool
		Dag                     *dagconfig.Config
		Consensus               *consensusconfig.Config
		DocRoot                 *string `toml:"-"`
	}
	var dec Config
	if err := unmarshal(&dec); err != nil {
		return err
	} /*
		if dec.Genesis != nil {
			c.Genesis = dec.Genesis
		}*/
	if dec.NetworkId != nil {
		c.NetworkId = *dec.NetworkId
	}
	if dec.SyncMode != nil {
		c.SyncMode = *dec.SyncMode
	}
	if dec.LightServ != nil {
		c.LightServ = *dec.LightServ
	}
	if dec.LightPeers != nil {
		c.LightPeers = *dec.LightPeers
	}
	if dec.SkipBcVersionCheck != nil {
		c.SkipBcVersionCheck = *dec.SkipBcVersionCheck
	}
	if dec.DatabaseHandles != nil {
		c.DatabaseHandles = *dec.DatabaseHandles
	}
	if dec.DatabaseCache != nil {
		c.DatabaseCache = *dec.DatabaseCache
	}
	if dec.Etherbase != nil {
		c.Etherbase = *dec.Etherbase
	}
	if dec.MinerThreads != nil {
		c.MinerThreads = *dec.MinerThreads
	}
	if dec.ExtraData != nil {
		c.ExtraData = *dec.ExtraData
	}
	if dec.GasPrice != nil {
		c.GasPrice = dec.GasPrice
	}
	/*wangjiyou
	if dec.Ethash != nil {
		c.Ethash = *dec.Ethash
	}*/
	if dec.TxPool != nil {
		c.TxPool = *dec.TxPool
	}
	if dec.GPO != nil {
		c.GPO = *dec.GPO
	}
	if dec.EnablePreimageRecording != nil {
		c.EnablePreimageRecording = *dec.EnablePreimageRecording
	}
	if dec.Dag != nil {
		c.Dag = *dec.Dag
	}
	if dec.DocRoot != nil {
		c.DocRoot = *dec.DocRoot
	}
	return nil
}
