// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode_shim.proto

package peer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED        ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER         ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED       ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT             ChaincodeMessage_Type = 3
	ChaincodeMessage_READY            ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION      ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED        ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR            ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE        ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE        ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE        ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE ChaincodeMessage_Type = 11
	ChaincodeMessage_RESPONSE         ChaincodeMessage_Type = 13
	//        GET_STATE_BY_RANGE = 14;
	//        GET_QUERY_RESULT = 15;
	//        QUERY_STATE_NEXT = 16;
	//        QUERY_STATE_CLOSE = 17;
	ChaincodeMessage_KEEPALIVE ChaincodeMessage_Type = 18
	//        GET_HISTORY_FOR_KEY = 19;
	ChaincodeMessage_OUTCHAIN_ADDRESS          ChaincodeMessage_Type = 20
	ChaincodeMessage_OUTCHAIN_TRANSACTION      ChaincodeMessage_Type = 21
	ChaincodeMessage_OUTCHAIN_QUERY            ChaincodeMessage_Type = 22
	ChaincodeMessage_GET_SYSTEM_CONFIG_REQUEST ChaincodeMessage_Type = 23
	ChaincodeMessage_GET_CONTRACT_ALL_STATE    ChaincodeMessage_Type = 24
	ChaincodeMessage_GET_TOKEN_BALANCE         ChaincodeMessage_Type = 25
	ChaincodeMessage_PAY_OUT_TOKEN             ChaincodeMessage_Type = 26
	ChaincodeMessage_DEFINE_TOKEN              ChaincodeMessage_Type = 27
	ChaincodeMessage_SUPPLY_TOKEN              ChaincodeMessage_Type = 28
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	13: "RESPONSE",
	18: "KEEPALIVE",
	20: "OUTCHAIN_ADDRESS",
	21: "OUTCHAIN_TRANSACTION",
	22: "OUTCHAIN_QUERY",
	23: "GET_SYSTEM_CONFIG_REQUEST",
	24: "GET_CONTRACT_ALL_STATE",
	25: "GET_TOKEN_BALANCE",
	26: "PAY_OUT_TOKEN",
	27: "DEFINE_TOKEN",
	28: "SUPPLY_TOKEN",
}

var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":                 0,
	"REGISTER":                  1,
	"REGISTERED":                2,
	"INIT":                      3,
	"READY":                     4,
	"TRANSACTION":               5,
	"COMPLETED":                 6,
	"ERROR":                     7,
	"GET_STATE":                 8,
	"PUT_STATE":                 9,
	"DEL_STATE":                 10,
	"INVOKE_CHAINCODE":          11,
	"RESPONSE":                  13,
	"KEEPALIVE":                 18,
	"OUTCHAIN_ADDRESS":          20,
	"OUTCHAIN_TRANSACTION":      21,
	"OUTCHAIN_QUERY":            22,
	"GET_SYSTEM_CONFIG_REQUEST": 23,
	"GET_CONTRACT_ALL_STATE":    24,
	"GET_TOKEN_BALANCE":         25,
	"PAY_OUT_TOKEN":             26,
	"DEFINE_TOKEN":              27,
	"SUPPLY_TOKEN":              28,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}

func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{0, 0}
}

type ChaincodeMessage struct {
	Type      ChaincodeMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   []byte                `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid      string                `protobuf:"bytes,4,opt,name=txid,proto3" json:"txid,omitempty"`
	Proposal  *SignedProposal       `protobuf:"bytes,5,opt,name=proposal,proto3" json:"proposal,omitempty"`
	//event emitted by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	//with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincode_event,json=chaincodeEvent,proto3" json:"chaincode_event,omitempty"`
	//channel id
	ChannelId string `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	//contract id
	ContractId           []byte   `protobuf:"bytes,8,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeMessage) Reset()         { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()    {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{0}
}

func (m *ChaincodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeMessage.Unmarshal(m, b)
}
func (m *ChaincodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeMessage.Marshal(b, m, deterministic)
}
func (m *ChaincodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeMessage.Merge(m, src)
}
func (m *ChaincodeMessage) XXX_Size() int {
	return xxx_messageInfo_ChaincodeMessage.Size(m)
}
func (m *ChaincodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeMessage proto.InternalMessageInfo

func (m *ChaincodeMessage) GetType() ChaincodeMessage_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeMessage_UNDEFINED
}

func (m *ChaincodeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChaincodeMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChaincodeMessage) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ChaincodeMessage) GetProposal() *SignedProposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

func (m *ChaincodeMessage) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ChaincodeMessage) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type GetState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{1}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type PutState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutState) Reset()         { *m = PutState{} }
func (m *PutState) String() string { return proto.CompactTextString(m) }
func (*PutState) ProtoMessage()    {}
func (*PutState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{2}
}

func (m *PutState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutState.Unmarshal(m, b)
}
func (m *PutState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutState.Marshal(b, m, deterministic)
}
func (m *PutState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutState.Merge(m, src)
}
func (m *PutState) XXX_Size() int {
	return xxx_messageInfo_PutState.Size(m)
}
func (m *PutState) XXX_DiscardUnknown() {
	xxx_messageInfo_PutState.DiscardUnknown(m)
}

var xxx_messageInfo_PutState proto.InternalMessageInfo

func (m *PutState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type DelState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelState) Reset()         { *m = DelState{} }
func (m *DelState) String() string { return proto.CompactTextString(m) }
func (*DelState) ProtoMessage()    {}
func (*DelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{3}
}

func (m *DelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelState.Unmarshal(m, b)
}
func (m *DelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelState.Marshal(b, m, deterministic)
}
func (m *DelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelState.Merge(m, src)
}
func (m *DelState) XXX_Size() int {
	return xxx_messageInfo_DelState.Size(m)
}
func (m *DelState) XXX_DiscardUnknown() {
	xxx_messageInfo_DelState.DiscardUnknown(m)
}

var xxx_messageInfo_DelState proto.InternalMessageInfo

func (m *DelState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DelState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetStateByRange struct {
	StartKey             string   `protobuf:"bytes,1,opt,name=startKey,proto3" json:"startKey,omitempty"`
	EndKey               string   `protobuf:"bytes,2,opt,name=endKey,proto3" json:"endKey,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateByRange) Reset()         { *m = GetStateByRange{} }
func (m *GetStateByRange) String() string { return proto.CompactTextString(m) }
func (*GetStateByRange) ProtoMessage()    {}
func (*GetStateByRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{4}
}

func (m *GetStateByRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateByRange.Unmarshal(m, b)
}
func (m *GetStateByRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateByRange.Marshal(b, m, deterministic)
}
func (m *GetStateByRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateByRange.Merge(m, src)
}
func (m *GetStateByRange) XXX_Size() int {
	return xxx_messageInfo_GetStateByRange.Size(m)
}
func (m *GetStateByRange) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateByRange.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateByRange proto.InternalMessageInfo

func (m *GetStateByRange) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *GetStateByRange) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *GetStateByRange) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetQueryResult struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQueryResult) Reset()         { *m = GetQueryResult{} }
func (m *GetQueryResult) String() string { return proto.CompactTextString(m) }
func (*GetQueryResult) ProtoMessage()    {}
func (*GetQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{5}
}

func (m *GetQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueryResult.Unmarshal(m, b)
}
func (m *GetQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueryResult.Marshal(b, m, deterministic)
}
func (m *GetQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueryResult.Merge(m, src)
}
func (m *GetQueryResult) XXX_Size() int {
	return xxx_messageInfo_GetQueryResult.Size(m)
}
func (m *GetQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueryResult proto.InternalMessageInfo

func (m *GetQueryResult) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GetQueryResult) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetHistoryForKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryForKey) Reset()         { *m = GetHistoryForKey{} }
func (m *GetHistoryForKey) String() string { return proto.CompactTextString(m) }
func (*GetHistoryForKey) ProtoMessage()    {}
func (*GetHistoryForKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{6}
}

func (m *GetHistoryForKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryForKey.Unmarshal(m, b)
}
func (m *GetHistoryForKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryForKey.Marshal(b, m, deterministic)
}
func (m *GetHistoryForKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryForKey.Merge(m, src)
}
func (m *GetHistoryForKey) XXX_Size() int {
	return xxx_messageInfo_GetHistoryForKey.Size(m)
}
func (m *GetHistoryForKey) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryForKey.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryForKey proto.InternalMessageInfo

func (m *GetHistoryForKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type QueryStateNext struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStateNext) Reset()         { *m = QueryStateNext{} }
func (m *QueryStateNext) String() string { return proto.CompactTextString(m) }
func (*QueryStateNext) ProtoMessage()    {}
func (*QueryStateNext) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{7}
}

func (m *QueryStateNext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStateNext.Unmarshal(m, b)
}
func (m *QueryStateNext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStateNext.Marshal(b, m, deterministic)
}
func (m *QueryStateNext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStateNext.Merge(m, src)
}
func (m *QueryStateNext) XXX_Size() int {
	return xxx_messageInfo_QueryStateNext.Size(m)
}
func (m *QueryStateNext) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStateNext.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStateNext proto.InternalMessageInfo

func (m *QueryStateNext) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryStateClose struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStateClose) Reset()         { *m = QueryStateClose{} }
func (m *QueryStateClose) String() string { return proto.CompactTextString(m) }
func (*QueryStateClose) ProtoMessage()    {}
func (*QueryStateClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{8}
}

func (m *QueryStateClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStateClose.Unmarshal(m, b)
}
func (m *QueryStateClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStateClose.Marshal(b, m, deterministic)
}
func (m *QueryStateClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStateClose.Merge(m, src)
}
func (m *QueryStateClose) XXX_Size() int {
	return xxx_messageInfo_QueryStateClose.Size(m)
}
func (m *QueryStateClose) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStateClose.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStateClose proto.InternalMessageInfo

func (m *QueryStateClose) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryResultBytes struct {
	ResultBytes          []byte   `protobuf:"bytes,1,opt,name=resultBytes,proto3" json:"resultBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResultBytes) Reset()         { *m = QueryResultBytes{} }
func (m *QueryResultBytes) String() string { return proto.CompactTextString(m) }
func (*QueryResultBytes) ProtoMessage()    {}
func (*QueryResultBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{9}
}

func (m *QueryResultBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultBytes.Unmarshal(m, b)
}
func (m *QueryResultBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultBytes.Marshal(b, m, deterministic)
}
func (m *QueryResultBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultBytes.Merge(m, src)
}
func (m *QueryResultBytes) XXX_Size() int {
	return xxx_messageInfo_QueryResultBytes.Size(m)
}
func (m *QueryResultBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultBytes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultBytes proto.InternalMessageInfo

func (m *QueryResultBytes) GetResultBytes() []byte {
	if m != nil {
		return m.ResultBytes
	}
	return nil
}

type QueryResponse struct {
	Results              []*QueryResultBytes `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore              bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Id                   string              `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{10}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*QueryResultBytes {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *QueryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type OutChainAddress struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainAddress) Reset()         { *m = OutChainAddress{} }
func (m *OutChainAddress) String() string { return proto.CompactTextString(m) }
func (*OutChainAddress) ProtoMessage()    {}
func (*OutChainAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{11}
}

func (m *OutChainAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainAddress.Unmarshal(m, b)
}
func (m *OutChainAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainAddress.Marshal(b, m, deterministic)
}
func (m *OutChainAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainAddress.Merge(m, src)
}
func (m *OutChainAddress) XXX_Size() int {
	return xxx_messageInfo_OutChainAddress.Size(m)
}
func (m *OutChainAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainAddress.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainAddress proto.InternalMessageInfo

func (m *OutChainAddress) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainAddress) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainAddress) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type OutChainTransaction struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainTransaction) Reset()         { *m = OutChainTransaction{} }
func (m *OutChainTransaction) String() string { return proto.CompactTextString(m) }
func (*OutChainTransaction) ProtoMessage()    {}
func (*OutChainTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{12}
}

func (m *OutChainTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainTransaction.Unmarshal(m, b)
}
func (m *OutChainTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainTransaction.Marshal(b, m, deterministic)
}
func (m *OutChainTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainTransaction.Merge(m, src)
}
func (m *OutChainTransaction) XXX_Size() int {
	return xxx_messageInfo_OutChainTransaction.Size(m)
}
func (m *OutChainTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainTransaction proto.InternalMessageInfo

func (m *OutChainTransaction) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainTransaction) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainTransaction) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type OutChainQuery struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainQuery) Reset()         { *m = OutChainQuery{} }
func (m *OutChainQuery) String() string { return proto.CompactTextString(m) }
func (*OutChainQuery) ProtoMessage()    {}
func (*OutChainQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{13}
}

func (m *OutChainQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainQuery.Unmarshal(m, b)
}
func (m *OutChainQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainQuery.Marshal(b, m, deterministic)
}
func (m *OutChainQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainQuery.Merge(m, src)
}
func (m *OutChainQuery) XXX_Size() int {
	return xxx_messageInfo_OutChainQuery.Size(m)
}
func (m *OutChainQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainQuery.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainQuery proto.InternalMessageInfo

func (m *OutChainQuery) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainQuery) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainQuery) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetTokenBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenBalance) Reset()         { *m = GetTokenBalance{} }
func (m *GetTokenBalance) String() string { return proto.CompactTextString(m) }
func (*GetTokenBalance) ProtoMessage()    {}
func (*GetTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{14}
}

func (m *GetTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenBalance.Unmarshal(m, b)
}
func (m *GetTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenBalance.Marshal(b, m, deterministic)
}
func (m *GetTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenBalance.Merge(m, src)
}
func (m *GetTokenBalance) XXX_Size() int {
	return xxx_messageInfo_GetTokenBalance.Size(m)
}
func (m *GetTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenBalance proto.InternalMessageInfo

func (m *GetTokenBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetTokenBalance) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type PayOutToken struct {
	Asset                []byte   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Locktime             uint32   `protobuf:"varint,3,opt,name=locktime,proto3" json:"locktime,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutToken) Reset()         { *m = PayOutToken{} }
func (m *PayOutToken) String() string { return proto.CompactTextString(m) }
func (*PayOutToken) ProtoMessage()    {}
func (*PayOutToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{15}
}

func (m *PayOutToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutToken.Unmarshal(m, b)
}
func (m *PayOutToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutToken.Marshal(b, m, deterministic)
}
func (m *PayOutToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutToken.Merge(m, src)
}
func (m *PayOutToken) XXX_Size() int {
	return xxx_messageInfo_PayOutToken.Size(m)
}
func (m *PayOutToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutToken.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutToken proto.InternalMessageInfo

func (m *PayOutToken) GetAsset() []byte {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *PayOutToken) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayOutToken) GetLocktime() uint32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *PayOutToken) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DefineToken struct {
	TokenType            int32    `protobuf:"varint,1,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Define               []byte   `protobuf:"bytes,2,opt,name=define,proto3" json:"define,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefineToken) Reset()         { *m = DefineToken{} }
func (m *DefineToken) String() string { return proto.CompactTextString(m) }
func (*DefineToken) ProtoMessage()    {}
func (*DefineToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{16}
}

func (m *DefineToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefineToken.Unmarshal(m, b)
}
func (m *DefineToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefineToken.Marshal(b, m, deterministic)
}
func (m *DefineToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefineToken.Merge(m, src)
}
func (m *DefineToken) XXX_Size() int {
	return xxx_messageInfo_DefineToken.Size(m)
}
func (m *DefineToken) XXX_DiscardUnknown() {
	xxx_messageInfo_DefineToken.DiscardUnknown(m)
}

var xxx_messageInfo_DefineToken proto.InternalMessageInfo

func (m *DefineToken) GetTokenType() int32 {
	if m != nil {
		return m.TokenType
	}
	return 0
}

func (m *DefineToken) GetDefine() []byte {
	if m != nil {
		return m.Define
	}
	return nil
}

type SupplyToken struct {
	AssetId              []byte   `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	UniqueId             []byte   `protobuf:"bytes,2,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupplyToken) Reset()         { *m = SupplyToken{} }
func (m *SupplyToken) String() string { return proto.CompactTextString(m) }
func (*SupplyToken) ProtoMessage()    {}
func (*SupplyToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{17}
}

func (m *SupplyToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplyToken.Unmarshal(m, b)
}
func (m *SupplyToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplyToken.Marshal(b, m, deterministic)
}
func (m *SupplyToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplyToken.Merge(m, src)
}
func (m *SupplyToken) XXX_Size() int {
	return xxx_messageInfo_SupplyToken.Size(m)
}
func (m *SupplyToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplyToken.DiscardUnknown(m)
}

var xxx_messageInfo_SupplyToken proto.InternalMessageInfo

func (m *SupplyToken) GetAssetId() []byte {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *SupplyToken) GetUniqueId() []byte {
	if m != nil {
		return m.UniqueId
	}
	return nil
}

func (m *SupplyToken) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type KeyForSystemConfig struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyForSystemConfig) Reset()         { *m = KeyForSystemConfig{} }
func (m *KeyForSystemConfig) String() string { return proto.CompactTextString(m) }
func (*KeyForSystemConfig) ProtoMessage()    {}
func (*KeyForSystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{18}
}

func (m *KeyForSystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyForSystemConfig.Unmarshal(m, b)
}
func (m *KeyForSystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyForSystemConfig.Marshal(b, m, deterministic)
}
func (m *KeyForSystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyForSystemConfig.Merge(m, src)
}
func (m *KeyForSystemConfig) XXX_Size() int {
	return xxx_messageInfo_KeyForSystemConfig.Size(m)
}
func (m *KeyForSystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyForSystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_KeyForSystemConfig proto.InternalMessageInfo

func (m *KeyForSystemConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
	proto.RegisterType((*ChaincodeMessage)(nil), "protos.ChaincodeMessage")
	proto.RegisterType((*GetState)(nil), "protos.GetState")
	proto.RegisterType((*PutState)(nil), "protos.PutState")
	proto.RegisterType((*DelState)(nil), "protos.DelState")
	proto.RegisterType((*GetStateByRange)(nil), "protos.GetStateByRange")
	proto.RegisterType((*GetQueryResult)(nil), "protos.GetQueryResult")
	proto.RegisterType((*GetHistoryForKey)(nil), "protos.GetHistoryForKey")
	proto.RegisterType((*QueryStateNext)(nil), "protos.QueryStateNext")
	proto.RegisterType((*QueryStateClose)(nil), "protos.QueryStateClose")
	proto.RegisterType((*QueryResultBytes)(nil), "protos.QueryResultBytes")
	proto.RegisterType((*QueryResponse)(nil), "protos.QueryResponse")
	proto.RegisterType((*OutChainAddress)(nil), "protos.OutChainAddress")
	proto.RegisterType((*OutChainTransaction)(nil), "protos.OutChainTransaction")
	proto.RegisterType((*OutChainQuery)(nil), "protos.OutChainQuery")
	proto.RegisterType((*GetTokenBalance)(nil), "protos.GetTokenBalance")
	proto.RegisterType((*PayOutToken)(nil), "protos.PayOutToken")
	proto.RegisterType((*DefineToken)(nil), "protos.DefineToken")
	proto.RegisterType((*SupplyToken)(nil), "protos.SupplyToken")
	proto.RegisterType((*KeyForSystemConfig)(nil), "protos.KeyForSystemConfig")
}

func init() { proto.RegisterFile("chaincode_shim.proto", fileDescriptor_adb8e00c9c92d6c8) }

var fileDescriptor_adb8e00c9c92d6c8 = []byte{
	// 1115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0xad, 0x63, 0x27, 0xb1, 0xaf, 0x13, 0x47, 0xe5, 0xd2, 0x4c, 0xf5, 0xda, 0x35, 0x13, 0x86,
	0x21, 0x2f, 0xb3, 0xb7, 0x6c, 0x0f, 0x7b, 0x28, 0xb0, 0x29, 0x12, 0x93, 0x0a, 0x49, 0x24, 0x97,
	0x92, 0x8b, 0x65, 0x7b, 0x30, 0x18, 0x89, 0xb5, 0x85, 0xc8, 0xa2, 0x22, 0x51, 0x45, 0xfd, 0x03,
	0xf6, 0x3f, 0xf6, 0x53, 0x07, 0xea, 0xc3, 0x76, 0x12, 0x14, 0x01, 0x56, 0xf4, 0xc9, 0x3a, 0xf7,
	0x9e, 0x7b, 0xee, 0xb9, 0x14, 0x69, 0x11, 0xf6, 0xfd, 0x19, 0x0d, 0x63, 0x9f, 0x07, 0x6c, 0x92,
	0xcd, 0xc2, 0xf9, 0x20, 0x49, 0xb9, 0xe0, 0x68, 0xab, 0xf8, 0xc9, 0xfa, 0xef, 0xa6, 0xa1, 0x98,
	0xe5, 0xd7, 0x03, 0x9f, 0xcf, 0x87, 0x09, 0x8d, 0x22, 0x26, 0x78, 0xcc, 0x86, 0x53, 0xfe, 0xe3,
	0x0a, 0xf8, 0x3c, 0x65, 0xc3, 0x0f, 0x73, 0x83, 0xc7, 0x22, 0xa5, 0xbe, 0x18, 0xe5, 0xd7, 0xc3,
	0xb2, 0x78, 0x98, 0x30, 0x96, 0x0e, 0x57, 0xf2, 0xec, 0x03, 0x8b, 0x45, 0xa9, 0xdf, 0x77, 0x3e,
	0x5b, 0x37, 0x49, 0x79, 0xc2, 0x33, 0x1a, 0x55, 0x82, 0xaf, 0xa6, 0x9c, 0x4f, 0x23, 0x56, 0x52,
	0xae, 0xf3, 0xf7, 0x43, 0x11, 0xce, 0x59, 0x26, 0xe8, 0x3c, 0x29, 0x09, 0xda, 0x3f, 0x5b, 0xa0,
	0x18, 0xb5, 0x97, 0x4b, 0x96, 0x65, 0x74, 0xca, 0xd0, 0xcf, 0xd0, 0x12, 0x8b, 0x84, 0xa9, 0x8d,
	0xc3, 0xc6, 0x51, 0xef, 0xf8, 0x65, 0x49, 0xcd, 0x06, 0xf7, 0x79, 0x03, 0x6f, 0x91, 0x30, 0x52,
	0x50, 0xd1, 0x6f, 0xd0, 0x59, 0x4a, 0xab, 0x1b, 0x87, 0x8d, 0xa3, 0xee, 0x71, 0x7f, 0x50, 0x36,
	0x1f, 0xd4, 0xcd, 0x07, 0x5e, 0xcd, 0x20, 0x2b, 0x32, 0x52, 0x61, 0x3b, 0xa1, 0x8b, 0x88, 0xd3,
	0x40, 0x6d, 0x1e, 0x36, 0x8e, 0x76, 0x48, 0x0d, 0x11, 0x82, 0x96, 0xf8, 0x18, 0x06, 0x6a, 0xeb,
	0xb0, 0x71, 0xd4, 0x21, 0xc5, 0x33, 0x3a, 0x86, 0x76, 0x3d, 0xa2, 0xba, 0x59, 0xb4, 0x39, 0xa8,
	0xed, 0xb9, 0xe1, 0x34, 0x66, 0xc1, 0xa8, 0xca, 0x92, 0x25, 0x0f, 0xfd, 0x0e, 0x7b, 0xf7, 0x96,
	0x5b, 0xdd, 0xba, 0x5b, 0xba, 0x9c, 0x0c, 0xcb, 0x2c, 0xe9, 0xf9, 0x77, 0x30, 0x7a, 0x09, 0xe0,
	0xcf, 0x68, 0x1c, 0xb3, 0x68, 0x12, 0x06, 0xea, 0x76, 0x61, 0xa7, 0x53, 0x45, 0xac, 0x00, 0xbd,
	0x82, 0xae, 0x5f, 0xbd, 0x0e, 0x99, 0x6f, 0x17, 0x53, 0x40, 0x1d, 0xb2, 0x02, 0xed, 0xdf, 0x26,
	0xb4, 0xe4, 0x5a, 0xa1, 0x5d, 0xe8, 0x8c, 0x6d, 0x13, 0x9f, 0x5a, 0x36, 0x36, 0x95, 0x27, 0x68,
	0x07, 0xda, 0x04, 0x9f, 0x59, 0xae, 0x87, 0x89, 0xd2, 0x40, 0x3d, 0x80, 0x1a, 0x61, 0x53, 0xd9,
	0x40, 0x6d, 0x68, 0x59, 0xb6, 0xe5, 0x29, 0x4d, 0xd4, 0x81, 0x4d, 0x82, 0x75, 0xf3, 0x4a, 0x69,
	0xa1, 0x3d, 0xe8, 0x7a, 0x44, 0xb7, 0x5d, 0xdd, 0xf0, 0x2c, 0xc7, 0x56, 0x36, 0xa5, 0xa4, 0xe1,
	0x5c, 0x8e, 0x2e, 0xb0, 0x87, 0x4d, 0x65, 0x4b, 0x52, 0x31, 0x21, 0x0e, 0x51, 0xb6, 0x65, 0xe6,
	0x0c, 0x7b, 0x13, 0xd7, 0xd3, 0x3d, 0xac, 0xb4, 0x25, 0x1c, 0x8d, 0x6b, 0xd8, 0x91, 0xd0, 0xc4,
	0x17, 0x15, 0x04, 0xb4, 0x0f, 0x8a, 0x65, 0xbf, 0x73, 0xce, 0xf1, 0xc4, 0x78, 0xa3, 0x5b, 0xb6,
	0xe1, 0x98, 0x58, 0xe9, 0x96, 0x06, 0xdd, 0x91, 0x63, 0xbb, 0x58, 0xd9, 0x95, 0x25, 0xe7, 0x18,
	0x8f, 0xf4, 0x0b, 0xeb, 0x1d, 0x56, 0x90, 0x2c, 0x71, 0xc6, 0x5e, 0x41, 0x9f, 0xe8, 0xa6, 0x49,
	0xb0, 0xeb, 0x2a, 0xfb, 0x48, 0x85, 0xfd, 0x65, 0x74, 0xdd, 0xe9, 0x33, 0x84, 0xa0, 0xb7, 0xcc,
	0xbc, 0x1d, 0x63, 0x72, 0xa5, 0x1c, 0xa0, 0x97, 0xf0, 0xbc, 0xf0, 0x78, 0xe5, 0x7a, 0xf8, 0x72,
	0x62, 0x38, 0xf6, 0xa9, 0x75, 0x36, 0x21, 0xf8, 0xed, 0x18, 0xbb, 0x9e, 0xf2, 0x35, 0xea, 0xc3,
	0x81, 0x4c, 0x1b, 0x8e, 0xed, 0x11, 0xdd, 0xf0, 0x26, 0xfa, 0x45, 0xed, 0x58, 0x45, 0xcf, 0xe0,
	0xa9, 0xcc, 0x79, 0xce, 0x39, 0xb6, 0x27, 0x27, 0xfa, 0x85, 0x6e, 0x1b, 0x58, 0x79, 0x8e, 0x9e,
	0xc2, 0xee, 0x48, 0xbf, 0x9a, 0x38, 0xe3, 0x2a, 0xa5, 0xf4, 0x91, 0x02, 0x3b, 0xe5, 0x9a, 0x57,
	0x91, 0x6f, 0x64, 0xc4, 0x1d, 0x8f, 0x46, 0x17, 0x57, 0x55, 0xe4, 0x85, 0xf6, 0x1a, 0xda, 0x67,
	0x4c, 0xb8, 0x82, 0x0a, 0x86, 0x14, 0x68, 0xde, 0xb0, 0x45, 0xb1, 0xfb, 0x3b, 0x44, 0x3e, 0xa2,
	0x6f, 0x01, 0x7c, 0x1e, 0x45, 0xcc, 0x17, 0x21, 0x8f, 0x8b, 0xed, 0xdd, 0x21, 0x6b, 0x11, 0x8d,
	0x40, 0x7b, 0x94, 0x7f, 0xb2, 0x7a, 0x1f, 0x36, 0x3f, 0xd0, 0x28, 0x67, 0x45, 0xe1, 0x0e, 0x29,
	0xc1, 0x3d, 0xcd, 0xe6, 0x03, 0xcd, 0xd7, 0xd0, 0x36, 0x59, 0xf4, 0x7f, 0x1d, 0x31, 0xd8, 0xab,
	0xe7, 0x39, 0x59, 0x10, 0x1a, 0x4f, 0x19, 0xea, 0x43, 0x3b, 0x13, 0x34, 0x15, 0xe7, 0x4b, 0xa5,
	0x25, 0x46, 0x07, 0xb0, 0xc5, 0xe2, 0x40, 0x66, 0x4a, 0xa9, 0x0a, 0x3d, 0x6a, 0xf2, 0x14, 0x7a,
	0x67, 0x4c, 0xbc, 0xcd, 0x59, 0xba, 0x20, 0x2c, 0xcb, 0x23, 0x21, 0x87, 0xbd, 0x95, 0xb0, 0x6a,
	0x51, 0x82, 0x47, 0xed, 0x7e, 0x0f, 0xca, 0x19, 0x13, 0x6f, 0xc2, 0x4c, 0xf0, 0x74, 0x71, 0xca,
	0x53, 0xd9, 0xfb, 0xc1, 0xd0, 0xda, 0x21, 0xf4, 0x8a, 0x56, 0xc5, 0x58, 0x36, 0xfb, 0x28, 0x50,
	0x0f, 0x36, 0xc2, 0xa0, 0xa2, 0x6c, 0x84, 0x81, 0xf6, 0x1d, 0xec, 0xad, 0x18, 0x46, 0xc4, 0x33,
	0xf6, 0x80, 0xf2, 0x2b, 0x28, 0x6b, 0x7e, 0x4f, 0x16, 0x82, 0x65, 0xe8, 0x10, 0xba, 0xe9, 0x0a,
	0x16, 0xe4, 0x1d, 0xb2, 0x1e, 0xd2, 0x62, 0xd8, 0xad, 0xab, 0x12, 0x1e, 0x67, 0x0c, 0x1d, 0xc3,
	0x76, 0x99, 0x97, 0xf4, 0xe6, 0x51, 0xf7, 0x58, 0xad, 0xff, 0x4c, 0xee, 0xab, 0x93, 0x9a, 0x88,
	0x9e, 0x43, 0x7b, 0x46, 0xb3, 0xc9, 0x9c, 0xa7, 0xe5, 0x5e, 0x68, 0x93, 0xed, 0x19, 0xcd, 0x2e,
	0x79, 0x5a, 0xbb, 0x6c, 0x2e, 0x5d, 0xce, 0x61, 0xcf, 0xc9, 0x45, 0xf1, 0xbf, 0xa4, 0x07, 0x41,
	0xca, 0xb2, 0x0c, 0x69, 0xb0, 0x53, 0x87, 0x6c, 0x3a, 0x67, 0xd5, 0x48, 0x77, 0x62, 0xf2, 0x3d,
	0x26, 0x34, 0xa5, 0xf3, 0xac, 0xda, 0x6b, 0x15, 0x7a, 0xf4, 0x3d, 0xde, 0xc2, 0x57, 0xb5, 0x8e,
	0x97, 0xd2, 0x38, 0xa3, 0x45, 0xf8, 0x8b, 0xb6, 0xbc, 0x81, 0xdd, 0x5a, 0xa7, 0x58, 0xb1, 0x2f,
	0xda, 0x4c, 0x2f, 0x8e, 0x83, 0xc7, 0x6f, 0x58, 0x7c, 0x42, 0x23, 0x1a, 0xfb, 0x4c, 0x7e, 0x77,
	0x68, 0xb9, 0xb2, 0x55, 0xa7, 0x1a, 0xca, 0x2d, 0x4c, 0xb3, 0x8c, 0x89, 0x6a, 0x9f, 0x96, 0x40,
	0xbb, 0x85, 0xee, 0x88, 0x2e, 0x9c, 0xbc, 0x54, 0x59, 0x91, 0xca, 0xcd, 0x52, 0x02, 0xe9, 0x8f,
	0xce, 0x79, 0x1e, 0x97, 0xb5, 0x2d, 0x52, 0x21, 0x79, 0xf6, 0x22, 0xee, 0xdf, 0xc8, 0xaf, 0x5e,
	0xe1, 0x6e, 0x97, 0x2c, 0xf1, 0xba, 0x91, 0xd6, 0x1d, 0x23, 0x9a, 0x01, 0x5d, 0x93, 0xbd, 0x0f,
	0x63, 0x56, 0xb6, 0x7c, 0x01, 0x1d, 0x21, 0x1f, 0xbc, 0xfa, 0xdb, 0xbc, 0x49, 0x56, 0x01, 0xd9,
	0x3a, 0x28, 0xc8, 0xf5, 0xd2, 0x94, 0x48, 0xfb, 0x1b, 0xba, 0x6e, 0x9e, 0x24, 0xd1, 0xa2, 0x14,
	0x91, 0xdd, 0xa4, 0x55, 0x2b, 0xa8, 0x9c, 0xd7, 0x50, 0x7a, 0xcc, 0xe3, 0xf0, 0x36, 0x67, 0x56,
	0x50, 0x49, 0x2c, 0xf1, 0xda, 0x5c, 0xcd, 0xf5, 0xb9, 0xb4, 0x1f, 0x00, 0x9d, 0x33, 0x79, 0x60,
	0xdd, 0x45, 0x26, 0x98, 0xbc, 0x95, 0xbc, 0x0f, 0xa7, 0x0f, 0x4f, 0xee, 0xf1, 0x9f, 0x6b, 0xb7,
	0x0c, 0xe9, 0x86, 0xa7, 0x02, 0x99, 0xd0, 0x26, 0x6c, 0x1a, 0x66, 0x82, 0xa5, 0x48, 0xfd, 0xd4,
	0x1d, 0xa3, 0xff, 0xc9, 0x8c, 0xf6, 0xe4, 0xa8, 0xf1, 0x53, 0xe3, 0xc4, 0x81, 0x6e, 0x45, 0x90,
	0xf7, 0x9f, 0xbf, 0xfe, 0xf8, 0xdc, 0x1b, 0xd4, 0x75, 0x79, 0xc7, 0xfb, 0xe5, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0x54, 0x63, 0x5a, 0x02, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeSupportClient is the client API for ChaincodeSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], "/protos.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChaincodeSupportServer is the server API for ChaincodeSupport service.
type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chaincode_shim.proto",
}
