// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode_shim.proto

package peer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED           ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER            ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED          ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                ChaincodeMessage_Type = 3
	ChaincodeMessage_READY               ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION         ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED           ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR               ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE           ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE           ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE           ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE    ChaincodeMessage_Type = 11
	ChaincodeMessage_RESPONSE            ChaincodeMessage_Type = 13
	ChaincodeMessage_GET_STATE_BY_PREFIX ChaincodeMessage_Type = 14
	//        GET_QUERY_RESULT = 15;
	//        QUERY_STATE_NEXT = 16;
	//        QUERY_STATE_CLOSE = 17;
	ChaincodeMessage_KEEPALIVE ChaincodeMessage_Type = 18
	//        GET_HISTORY_FOR_KEY = 19;
	ChaincodeMessage_GET_SYSTEM_CONFIG_REQUEST ChaincodeMessage_Type = 23
	ChaincodeMessage_GET_CONTRACT_ALL_STATE    ChaincodeMessage_Type = 24
	ChaincodeMessage_GET_TOKEN_BALANCE         ChaincodeMessage_Type = 25
	ChaincodeMessage_PAY_OUT_TOKEN             ChaincodeMessage_Type = 26
	ChaincodeMessage_DEFINE_TOKEN              ChaincodeMessage_Type = 27
	ChaincodeMessage_SUPPLY_TOKEN              ChaincodeMessage_Type = 28
	ChaincodeMessage_GET_TIMESTAMP             ChaincodeMessage_Type = 29
	ChaincodeMessage_SEND_JURY                 ChaincodeMessage_Type = 30
	ChaincodeMessage_RECV_JURY                 ChaincodeMessage_Type = 31
	ChaincodeMessage_GET_CERT_STATE            ChaincodeMessage_Type = 32
	ChaincodeMessage_OUTCHAIN_CALL             ChaincodeMessage_Type = 33
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	13: "RESPONSE",
	14: "GET_STATE_BY_PREFIX",
	18: "KEEPALIVE",
	23: "GET_SYSTEM_CONFIG_REQUEST",
	24: "GET_CONTRACT_ALL_STATE",
	25: "GET_TOKEN_BALANCE",
	26: "PAY_OUT_TOKEN",
	27: "DEFINE_TOKEN",
	28: "SUPPLY_TOKEN",
	29: "GET_TIMESTAMP",
	30: "SEND_JURY",
	31: "RECV_JURY",
	32: "GET_CERT_STATE",
	33: "OUTCHAIN_CALL",
}

var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":                 0,
	"REGISTER":                  1,
	"REGISTERED":                2,
	"INIT":                      3,
	"READY":                     4,
	"TRANSACTION":               5,
	"COMPLETED":                 6,
	"ERROR":                     7,
	"GET_STATE":                 8,
	"PUT_STATE":                 9,
	"DEL_STATE":                 10,
	"INVOKE_CHAINCODE":          11,
	"RESPONSE":                  13,
	"GET_STATE_BY_PREFIX":       14,
	"KEEPALIVE":                 18,
	"GET_SYSTEM_CONFIG_REQUEST": 23,
	"GET_CONTRACT_ALL_STATE":    24,
	"GET_TOKEN_BALANCE":         25,
	"PAY_OUT_TOKEN":             26,
	"DEFINE_TOKEN":              27,
	"SUPPLY_TOKEN":              28,
	"GET_TIMESTAMP":             29,
	"SEND_JURY":                 30,
	"RECV_JURY":                 31,
	"GET_CERT_STATE":            32,
	"OUTCHAIN_CALL":             33,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}

func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{0, 0}
}

type ChaincodeMessage struct {
	Type      ChaincodeMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   []byte                `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid      string                `protobuf:"bytes,4,opt,name=txid,proto3" json:"txid,omitempty"`
	Proposal  *SignedProposal       `protobuf:"bytes,5,opt,name=proposal,proto3" json:"proposal,omitempty"`
	//event emitted by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	//with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincode_event,json=chaincodeEvent,proto3" json:"chaincode_event,omitempty"`
	//channel id
	ChannelId string `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	//contract id
	ContractId           []byte   `protobuf:"bytes,8,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeMessage) Reset()         { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()    {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{0}
}

func (m *ChaincodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeMessage.Unmarshal(m, b)
}
func (m *ChaincodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeMessage.Marshal(b, m, deterministic)
}
func (m *ChaincodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeMessage.Merge(m, src)
}
func (m *ChaincodeMessage) XXX_Size() int {
	return xxx_messageInfo_ChaincodeMessage.Size(m)
}
func (m *ChaincodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeMessage proto.InternalMessageInfo

func (m *ChaincodeMessage) GetType() ChaincodeMessage_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeMessage_UNDEFINED
}

func (m *ChaincodeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChaincodeMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChaincodeMessage) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ChaincodeMessage) GetProposal() *SignedProposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

func (m *ChaincodeMessage) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ChaincodeMessage) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type GetState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	ContractId           []byte   `protobuf:"bytes,3,opt,name=contractId,proto3" json:"contractId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{1}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *GetState) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type GetStateByPrefix struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ContractId           []byte   `protobuf:"bytes,2,opt,name=contractId,proto3" json:"contractId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateByPrefix) Reset()         { *m = GetStateByPrefix{} }
func (m *GetStateByPrefix) String() string { return proto.CompactTextString(m) }
func (*GetStateByPrefix) ProtoMessage()    {}
func (*GetStateByPrefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{2}
}

func (m *GetStateByPrefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateByPrefix.Unmarshal(m, b)
}
func (m *GetStateByPrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateByPrefix.Marshal(b, m, deterministic)
}
func (m *GetStateByPrefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateByPrefix.Merge(m, src)
}
func (m *GetStateByPrefix) XXX_Size() int {
	return xxx_messageInfo_GetStateByPrefix.Size(m)
}
func (m *GetStateByPrefix) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateByPrefix.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateByPrefix proto.InternalMessageInfo

func (m *GetStateByPrefix) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *GetStateByPrefix) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type GetTimestamp struct {
	RangeNumber          uint32   `protobuf:"varint,1,opt,name=rangeNumber,proto3" json:"rangeNumber,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimestamp) Reset()         { *m = GetTimestamp{} }
func (m *GetTimestamp) String() string { return proto.CompactTextString(m) }
func (*GetTimestamp) ProtoMessage()    {}
func (*GetTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{3}
}

func (m *GetTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimestamp.Unmarshal(m, b)
}
func (m *GetTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimestamp.Marshal(b, m, deterministic)
}
func (m *GetTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimestamp.Merge(m, src)
}
func (m *GetTimestamp) XXX_Size() int {
	return xxx_messageInfo_GetTimestamp.Size(m)
}
func (m *GetTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimestamp proto.InternalMessageInfo

func (m *GetTimestamp) GetRangeNumber() uint32 {
	if m != nil {
		return m.RangeNumber
	}
	return 0
}

func (m *GetTimestamp) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type PutState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	ContractId           []byte   `protobuf:"bytes,4,opt,name=contractId,proto3" json:"contractId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutState) Reset()         { *m = PutState{} }
func (m *PutState) String() string { return proto.CompactTextString(m) }
func (*PutState) ProtoMessage()    {}
func (*PutState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{4}
}

func (m *PutState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutState.Unmarshal(m, b)
}
func (m *PutState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutState.Marshal(b, m, deterministic)
}
func (m *PutState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutState.Merge(m, src)
}
func (m *PutState) XXX_Size() int {
	return xxx_messageInfo_PutState.Size(m)
}
func (m *PutState) XXX_DiscardUnknown() {
	xxx_messageInfo_PutState.DiscardUnknown(m)
}

var xxx_messageInfo_PutState proto.InternalMessageInfo

func (m *PutState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *PutState) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type DelState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	ContractId           []byte   `protobuf:"bytes,3,opt,name=contractId,proto3" json:"contractId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelState) Reset()         { *m = DelState{} }
func (m *DelState) String() string { return proto.CompactTextString(m) }
func (*DelState) ProtoMessage()    {}
func (*DelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{5}
}

func (m *DelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelState.Unmarshal(m, b)
}
func (m *DelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelState.Marshal(b, m, deterministic)
}
func (m *DelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelState.Merge(m, src)
}
func (m *DelState) XXX_Size() int {
	return xxx_messageInfo_DelState.Size(m)
}
func (m *DelState) XXX_DiscardUnknown() {
	xxx_messageInfo_DelState.DiscardUnknown(m)
}

var xxx_messageInfo_DelState proto.InternalMessageInfo

func (m *DelState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DelState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *DelState) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type GetStateByRange struct {
	StartKey             string   `protobuf:"bytes,1,opt,name=startKey,proto3" json:"startKey,omitempty"`
	EndKey               string   `protobuf:"bytes,2,opt,name=endKey,proto3" json:"endKey,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateByRange) Reset()         { *m = GetStateByRange{} }
func (m *GetStateByRange) String() string { return proto.CompactTextString(m) }
func (*GetStateByRange) ProtoMessage()    {}
func (*GetStateByRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{6}
}

func (m *GetStateByRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateByRange.Unmarshal(m, b)
}
func (m *GetStateByRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateByRange.Marshal(b, m, deterministic)
}
func (m *GetStateByRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateByRange.Merge(m, src)
}
func (m *GetStateByRange) XXX_Size() int {
	return xxx_messageInfo_GetStateByRange.Size(m)
}
func (m *GetStateByRange) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateByRange.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateByRange proto.InternalMessageInfo

func (m *GetStateByRange) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *GetStateByRange) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *GetStateByRange) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetQueryResult struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQueryResult) Reset()         { *m = GetQueryResult{} }
func (m *GetQueryResult) String() string { return proto.CompactTextString(m) }
func (*GetQueryResult) ProtoMessage()    {}
func (*GetQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{7}
}

func (m *GetQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueryResult.Unmarshal(m, b)
}
func (m *GetQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueryResult.Marshal(b, m, deterministic)
}
func (m *GetQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueryResult.Merge(m, src)
}
func (m *GetQueryResult) XXX_Size() int {
	return xxx_messageInfo_GetQueryResult.Size(m)
}
func (m *GetQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueryResult proto.InternalMessageInfo

func (m *GetQueryResult) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GetQueryResult) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetHistoryForKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryForKey) Reset()         { *m = GetHistoryForKey{} }
func (m *GetHistoryForKey) String() string { return proto.CompactTextString(m) }
func (*GetHistoryForKey) ProtoMessage()    {}
func (*GetHistoryForKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{8}
}

func (m *GetHistoryForKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryForKey.Unmarshal(m, b)
}
func (m *GetHistoryForKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryForKey.Marshal(b, m, deterministic)
}
func (m *GetHistoryForKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryForKey.Merge(m, src)
}
func (m *GetHistoryForKey) XXX_Size() int {
	return xxx_messageInfo_GetHistoryForKey.Size(m)
}
func (m *GetHistoryForKey) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryForKey.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryForKey proto.InternalMessageInfo

func (m *GetHistoryForKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type QueryStateNext struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStateNext) Reset()         { *m = QueryStateNext{} }
func (m *QueryStateNext) String() string { return proto.CompactTextString(m) }
func (*QueryStateNext) ProtoMessage()    {}
func (*QueryStateNext) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{9}
}

func (m *QueryStateNext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStateNext.Unmarshal(m, b)
}
func (m *QueryStateNext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStateNext.Marshal(b, m, deterministic)
}
func (m *QueryStateNext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStateNext.Merge(m, src)
}
func (m *QueryStateNext) XXX_Size() int {
	return xxx_messageInfo_QueryStateNext.Size(m)
}
func (m *QueryStateNext) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStateNext.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStateNext proto.InternalMessageInfo

func (m *QueryStateNext) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryStateClose struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStateClose) Reset()         { *m = QueryStateClose{} }
func (m *QueryStateClose) String() string { return proto.CompactTextString(m) }
func (*QueryStateClose) ProtoMessage()    {}
func (*QueryStateClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{10}
}

func (m *QueryStateClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStateClose.Unmarshal(m, b)
}
func (m *QueryStateClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStateClose.Marshal(b, m, deterministic)
}
func (m *QueryStateClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStateClose.Merge(m, src)
}
func (m *QueryStateClose) XXX_Size() int {
	return xxx_messageInfo_QueryStateClose.Size(m)
}
func (m *QueryStateClose) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStateClose.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStateClose proto.InternalMessageInfo

func (m *QueryStateClose) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryResultBytes struct {
	ResultBytes          []byte   `protobuf:"bytes,1,opt,name=resultBytes,proto3" json:"resultBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResultBytes) Reset()         { *m = QueryResultBytes{} }
func (m *QueryResultBytes) String() string { return proto.CompactTextString(m) }
func (*QueryResultBytes) ProtoMessage()    {}
func (*QueryResultBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{11}
}

func (m *QueryResultBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultBytes.Unmarshal(m, b)
}
func (m *QueryResultBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultBytes.Marshal(b, m, deterministic)
}
func (m *QueryResultBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultBytes.Merge(m, src)
}
func (m *QueryResultBytes) XXX_Size() int {
	return xxx_messageInfo_QueryResultBytes.Size(m)
}
func (m *QueryResultBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultBytes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultBytes proto.InternalMessageInfo

func (m *QueryResultBytes) GetResultBytes() []byte {
	if m != nil {
		return m.ResultBytes
	}
	return nil
}

type QueryResponse struct {
	Results              []*QueryResultBytes `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore              bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Id                   string              `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{12}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*QueryResultBytes {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *QueryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type OutChainCall struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params               []byte   `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainCall) Reset()         { *m = OutChainCall{} }
func (m *OutChainCall) String() string { return proto.CompactTextString(m) }
func (*OutChainCall) ProtoMessage()    {}
func (*OutChainCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{13}
}

func (m *OutChainCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainCall.Unmarshal(m, b)
}
func (m *OutChainCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainCall.Marshal(b, m, deterministic)
}
func (m *OutChainCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainCall.Merge(m, src)
}
func (m *OutChainCall) XXX_Size() int {
	return xxx_messageInfo_OutChainCall.Size(m)
}
func (m *OutChainCall) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainCall.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainCall proto.InternalMessageInfo

func (m *OutChainCall) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainCall) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *OutChainCall) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainCall) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetCertState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCertState) Reset()         { *m = GetCertState{} }
func (m *GetCertState) String() string { return proto.CompactTextString(m) }
func (*GetCertState) ProtoMessage()    {}
func (*GetCertState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{14}
}

func (m *GetCertState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCertState.Unmarshal(m, b)
}
func (m *GetCertState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCertState.Marshal(b, m, deterministic)
}
func (m *GetCertState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCertState.Merge(m, src)
}
func (m *GetCertState) XXX_Size() int {
	return xxx_messageInfo_GetCertState.Size(m)
}
func (m *GetCertState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCertState.DiscardUnknown(m)
}

var xxx_messageInfo_GetCertState proto.InternalMessageInfo

func (m *GetCertState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetCertState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type SendJury struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	ConsultContent       []byte   `protobuf:"bytes,2,opt,name=consultContent,proto3" json:"consultContent,omitempty"`
	MyAnswer             []byte   `protobuf:"bytes,3,opt,name=myAnswer,proto3" json:"myAnswer,omitempty"`
	Collection           string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendJury) Reset()         { *m = SendJury{} }
func (m *SendJury) String() string { return proto.CompactTextString(m) }
func (*SendJury) ProtoMessage()    {}
func (*SendJury) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{15}
}

func (m *SendJury) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJury.Unmarshal(m, b)
}
func (m *SendJury) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJury.Marshal(b, m, deterministic)
}
func (m *SendJury) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJury.Merge(m, src)
}
func (m *SendJury) XXX_Size() int {
	return xxx_messageInfo_SendJury.Size(m)
}
func (m *SendJury) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJury.DiscardUnknown(m)
}

var xxx_messageInfo_SendJury proto.InternalMessageInfo

func (m *SendJury) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *SendJury) GetConsultContent() []byte {
	if m != nil {
		return m.ConsultContent
	}
	return nil
}

func (m *SendJury) GetMyAnswer() []byte {
	if m != nil {
		return m.MyAnswer
	}
	return nil
}

func (m *SendJury) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type RecvJury struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	ConsultContent       []byte   `protobuf:"bytes,2,opt,name=consultContent,proto3" json:"consultContent,omitempty"`
	Timeout              uint32   `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Collection           string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecvJury) Reset()         { *m = RecvJury{} }
func (m *RecvJury) String() string { return proto.CompactTextString(m) }
func (*RecvJury) ProtoMessage()    {}
func (*RecvJury) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{16}
}

func (m *RecvJury) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecvJury.Unmarshal(m, b)
}
func (m *RecvJury) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecvJury.Marshal(b, m, deterministic)
}
func (m *RecvJury) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecvJury.Merge(m, src)
}
func (m *RecvJury) XXX_Size() int {
	return xxx_messageInfo_RecvJury.Size(m)
}
func (m *RecvJury) XXX_DiscardUnknown() {
	xxx_messageInfo_RecvJury.DiscardUnknown(m)
}

var xxx_messageInfo_RecvJury proto.InternalMessageInfo

func (m *RecvJury) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *RecvJury) GetConsultContent() []byte {
	if m != nil {
		return m.ConsultContent
	}
	return nil
}

func (m *RecvJury) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RecvJury) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetTokenBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenBalance) Reset()         { *m = GetTokenBalance{} }
func (m *GetTokenBalance) String() string { return proto.CompactTextString(m) }
func (*GetTokenBalance) ProtoMessage()    {}
func (*GetTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{17}
}

func (m *GetTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenBalance.Unmarshal(m, b)
}
func (m *GetTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenBalance.Marshal(b, m, deterministic)
}
func (m *GetTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenBalance.Merge(m, src)
}
func (m *GetTokenBalance) XXX_Size() int {
	return xxx_messageInfo_GetTokenBalance.Size(m)
}
func (m *GetTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenBalance proto.InternalMessageInfo

func (m *GetTokenBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetTokenBalance) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type PayOutToken struct {
	Asset                []byte   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Locktime             uint32   `protobuf:"varint,3,opt,name=locktime,proto3" json:"locktime,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutToken) Reset()         { *m = PayOutToken{} }
func (m *PayOutToken) String() string { return proto.CompactTextString(m) }
func (*PayOutToken) ProtoMessage()    {}
func (*PayOutToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{18}
}

func (m *PayOutToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutToken.Unmarshal(m, b)
}
func (m *PayOutToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutToken.Marshal(b, m, deterministic)
}
func (m *PayOutToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutToken.Merge(m, src)
}
func (m *PayOutToken) XXX_Size() int {
	return xxx_messageInfo_PayOutToken.Size(m)
}
func (m *PayOutToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutToken.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutToken proto.InternalMessageInfo

func (m *PayOutToken) GetAsset() []byte {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *PayOutToken) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayOutToken) GetLocktime() uint32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *PayOutToken) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DefineToken struct {
	TokenType            int32    `protobuf:"varint,1,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Define               []byte   `protobuf:"bytes,2,opt,name=define,proto3" json:"define,omitempty"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefineToken) Reset()         { *m = DefineToken{} }
func (m *DefineToken) String() string { return proto.CompactTextString(m) }
func (*DefineToken) ProtoMessage()    {}
func (*DefineToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{19}
}

func (m *DefineToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefineToken.Unmarshal(m, b)
}
func (m *DefineToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefineToken.Marshal(b, m, deterministic)
}
func (m *DefineToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefineToken.Merge(m, src)
}
func (m *DefineToken) XXX_Size() int {
	return xxx_messageInfo_DefineToken.Size(m)
}
func (m *DefineToken) XXX_DiscardUnknown() {
	xxx_messageInfo_DefineToken.DiscardUnknown(m)
}

var xxx_messageInfo_DefineToken proto.InternalMessageInfo

func (m *DefineToken) GetTokenType() int32 {
	if m != nil {
		return m.TokenType
	}
	return 0
}

func (m *DefineToken) GetDefine() []byte {
	if m != nil {
		return m.Define
	}
	return nil
}

func (m *DefineToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type SupplyToken struct {
	AssetId              []byte   `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	UniqueId             []byte   `protobuf:"bytes,2,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Creator              string   `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupplyToken) Reset()         { *m = SupplyToken{} }
func (m *SupplyToken) String() string { return proto.CompactTextString(m) }
func (*SupplyToken) ProtoMessage()    {}
func (*SupplyToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{20}
}

func (m *SupplyToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplyToken.Unmarshal(m, b)
}
func (m *SupplyToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplyToken.Marshal(b, m, deterministic)
}
func (m *SupplyToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplyToken.Merge(m, src)
}
func (m *SupplyToken) XXX_Size() int {
	return xxx_messageInfo_SupplyToken.Size(m)
}
func (m *SupplyToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplyToken.DiscardUnknown(m)
}

var xxx_messageInfo_SupplyToken proto.InternalMessageInfo

func (m *SupplyToken) GetAssetId() []byte {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *SupplyToken) GetUniqueId() []byte {
	if m != nil {
		return m.UniqueId
	}
	return nil
}

func (m *SupplyToken) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SupplyToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type KeyForSystemConfig struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyForSystemConfig) Reset()         { *m = KeyForSystemConfig{} }
func (m *KeyForSystemConfig) String() string { return proto.CompactTextString(m) }
func (*KeyForSystemConfig) ProtoMessage()    {}
func (*KeyForSystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{21}
}

func (m *KeyForSystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyForSystemConfig.Unmarshal(m, b)
}
func (m *KeyForSystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyForSystemConfig.Marshal(b, m, deterministic)
}
func (m *KeyForSystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyForSystemConfig.Merge(m, src)
}
func (m *KeyForSystemConfig) XXX_Size() int {
	return xxx_messageInfo_KeyForSystemConfig.Size(m)
}
func (m *KeyForSystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyForSystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_KeyForSystemConfig proto.InternalMessageInfo

func (m *KeyForSystemConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetStateByPrefixKv struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ResultBytes          []byte   `protobuf:"bytes,2,opt,name=resultBytes,proto3" json:"resultBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateByPrefixKv) Reset()         { *m = GetStateByPrefixKv{} }
func (m *GetStateByPrefixKv) String() string { return proto.CompactTextString(m) }
func (*GetStateByPrefixKv) ProtoMessage()    {}
func (*GetStateByPrefixKv) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{22}
}

func (m *GetStateByPrefixKv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateByPrefixKv.Unmarshal(m, b)
}
func (m *GetStateByPrefixKv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateByPrefixKv.Marshal(b, m, deterministic)
}
func (m *GetStateByPrefixKv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateByPrefixKv.Merge(m, src)
}
func (m *GetStateByPrefixKv) XXX_Size() int {
	return xxx_messageInfo_GetStateByPrefixKv.Size(m)
}
func (m *GetStateByPrefixKv) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateByPrefixKv.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateByPrefixKv proto.InternalMessageInfo

func (m *GetStateByPrefixKv) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetStateByPrefixKv) GetResultBytes() []byte {
	if m != nil {
		return m.ResultBytes
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
	proto.RegisterType((*ChaincodeMessage)(nil), "protos.ChaincodeMessage")
	proto.RegisterType((*GetState)(nil), "protos.GetState")
	proto.RegisterType((*GetStateByPrefix)(nil), "protos.GetStateByPrefix")
	proto.RegisterType((*GetTimestamp)(nil), "protos.GetTimestamp")
	proto.RegisterType((*PutState)(nil), "protos.PutState")
	proto.RegisterType((*DelState)(nil), "protos.DelState")
	proto.RegisterType((*GetStateByRange)(nil), "protos.GetStateByRange")
	proto.RegisterType((*GetQueryResult)(nil), "protos.GetQueryResult")
	proto.RegisterType((*GetHistoryForKey)(nil), "protos.GetHistoryForKey")
	proto.RegisterType((*QueryStateNext)(nil), "protos.QueryStateNext")
	proto.RegisterType((*QueryStateClose)(nil), "protos.QueryStateClose")
	proto.RegisterType((*QueryResultBytes)(nil), "protos.QueryResultBytes")
	proto.RegisterType((*QueryResponse)(nil), "protos.QueryResponse")
	proto.RegisterType((*OutChainCall)(nil), "protos.OutChainCall")
	proto.RegisterType((*GetCertState)(nil), "protos.GetCertState")
	proto.RegisterType((*SendJury)(nil), "protos.SendJury")
	proto.RegisterType((*RecvJury)(nil), "protos.RecvJury")
	proto.RegisterType((*GetTokenBalance)(nil), "protos.GetTokenBalance")
	proto.RegisterType((*PayOutToken)(nil), "protos.PayOutToken")
	proto.RegisterType((*DefineToken)(nil), "protos.DefineToken")
	proto.RegisterType((*SupplyToken)(nil), "protos.SupplyToken")
	proto.RegisterType((*KeyForSystemConfig)(nil), "protos.KeyForSystemConfig")
	proto.RegisterType((*GetStateByPrefixKv)(nil), "protos.GetStateByPrefixKv")
}

func init() { proto.RegisterFile("chaincode_shim.proto", fileDescriptor_adb8e00c9c92d6c8) }

var fileDescriptor_adb8e00c9c92d6c8 = []byte{
	// 1316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdf, 0x52, 0xdb, 0xc6,
	0x17, 0x8e, 0xb1, 0x01, 0xfb, 0x18, 0x8c, 0xb2, 0xbf, 0xfc, 0x12, 0x87, 0x86, 0x84, 0x68, 0x3a,
	0x19, 0x6e, 0x0a, 0x2d, 0xed, 0x45, 0xef, 0x1a, 0x21, 0x2f, 0x44, 0xc1, 0x48, 0xca, 0x4a, 0x66,
	0x42, 0x27, 0x1d, 0x8d, 0x90, 0x16, 0x5b, 0x13, 0x59, 0xeb, 0x48, 0x2b, 0x1a, 0xdf, 0xf6, 0xa2,
	0xd3, 0xe7, 0xe9, 0x7b, 0xf4, 0x9d, 0x3a, 0x2b, 0xad, 0x6c, 0x63, 0x92, 0x61, 0xa6, 0x69, 0xaf,
	0xf0, 0x77, 0xce, 0xd1, 0x77, 0xbe, 0x73, 0xf6, 0xec, 0x1f, 0xe0, 0x41, 0x30, 0xf2, 0xa3, 0x24,
	0x60, 0x21, 0xf5, 0xb2, 0x51, 0x34, 0xde, 0x9f, 0xa4, 0x8c, 0x33, 0xb4, 0x56, 0xfc, 0xc9, 0xb6,
	0xcf, 0x87, 0x11, 0x1f, 0xe5, 0x97, 0xfb, 0x01, 0x1b, 0x1f, 0x4c, 0xfc, 0x38, 0xa6, 0x9c, 0x25,
	0xf4, 0x60, 0xc8, 0xbe, 0x99, 0x83, 0x80, 0xa5, 0xf4, 0xe0, 0x7a, 0xac, 0xb3, 0x84, 0xa7, 0x7e,
	0xc0, 0xed, 0xfc, 0xf2, 0xa0, 0xfc, 0xf8, 0x60, 0x42, 0x69, 0x7a, 0x30, 0xa7, 0xa7, 0xd7, 0x34,
	0xe1, 0x25, 0xff, 0xb6, 0xf5, 0xc5, 0xbc, 0x93, 0x94, 0x4d, 0x58, 0xe6, 0xc7, 0x92, 0xf0, 0xd9,
	0x90, 0xb1, 0x61, 0x4c, 0xcb, 0x90, 0xcb, 0xfc, 0xea, 0x80, 0x47, 0x63, 0x9a, 0x71, 0x7f, 0x3c,
	0x29, 0x03, 0xd4, 0x3f, 0xd7, 0x40, 0xd1, 0x2b, 0x2d, 0x67, 0x34, 0xcb, 0xfc, 0x21, 0x45, 0xdf,
	0x41, 0x83, 0x4f, 0x27, 0xb4, 0x5b, 0xdb, 0xad, 0xed, 0x75, 0x0e, 0x77, 0xca, 0xd0, 0x6c, 0x7f,
	0x39, 0x6e, 0xdf, 0x9d, 0x4e, 0x28, 0x29, 0x42, 0xd1, 0x8f, 0xd0, 0x9a, 0x51, 0x77, 0x57, 0x76,
	0x6b, 0x7b, 0xed, 0xc3, 0xed, 0xfd, 0x32, 0xf9, 0x7e, 0x95, 0x7c, 0xdf, 0xad, 0x22, 0xc8, 0x3c,
	0x18, 0x75, 0x61, 0x7d, 0xe2, 0x4f, 0x63, 0xe6, 0x87, 0xdd, 0xfa, 0x6e, 0x6d, 0x6f, 0x83, 0x54,
	0x10, 0x21, 0x68, 0xf0, 0x8f, 0x51, 0xd8, 0x6d, 0xec, 0xd6, 0xf6, 0x5a, 0xa4, 0xf8, 0x8d, 0x0e,
	0xa1, 0x59, 0x95, 0xd8, 0x5d, 0x2d, 0xd2, 0x3c, 0xac, 0xe4, 0x39, 0xd1, 0x30, 0xa1, 0xa1, 0x2d,
	0xbd, 0x64, 0x16, 0x87, 0x7e, 0x82, 0xad, 0xa5, 0x76, 0x77, 0xd7, 0x6e, 0x7e, 0x3a, 0xab, 0x0c,
	0x0b, 0x2f, 0xe9, 0x04, 0x37, 0x30, 0xda, 0x01, 0x08, 0x46, 0x7e, 0x92, 0xd0, 0xd8, 0x8b, 0xc2,
	0xee, 0x7a, 0x21, 0xa7, 0x25, 0x2d, 0x46, 0x88, 0x9e, 0x41, 0x3b, 0x90, 0xcb, 0x21, 0xfc, 0xcd,
	0xa2, 0x0a, 0xa8, 0x4c, 0x46, 0xa8, 0xfe, 0x55, 0x87, 0x86, 0xe8, 0x15, 0xda, 0x84, 0xd6, 0xc0,
	0xec, 0xe1, 0x63, 0xc3, 0xc4, 0x3d, 0xe5, 0x1e, 0xda, 0x80, 0x26, 0xc1, 0x27, 0x86, 0xe3, 0x62,
	0xa2, 0xd4, 0x50, 0x07, 0xa0, 0x42, 0xb8, 0xa7, 0xac, 0xa0, 0x26, 0x34, 0x0c, 0xd3, 0x70, 0x95,
	0x3a, 0x6a, 0xc1, 0x2a, 0xc1, 0x5a, 0xef, 0x42, 0x69, 0xa0, 0x2d, 0x68, 0xbb, 0x44, 0x33, 0x1d,
	0x4d, 0x77, 0x0d, 0xcb, 0x54, 0x56, 0x05, 0xa5, 0x6e, 0x9d, 0xd9, 0x7d, 0xec, 0xe2, 0x9e, 0xb2,
	0x26, 0x42, 0x31, 0x21, 0x16, 0x51, 0xd6, 0x85, 0xe7, 0x04, 0xbb, 0x9e, 0xe3, 0x6a, 0x2e, 0x56,
	0x9a, 0x02, 0xda, 0x83, 0x0a, 0xb6, 0x04, 0xec, 0xe1, 0xbe, 0x84, 0x80, 0x1e, 0x80, 0x62, 0x98,
	0xe7, 0xd6, 0x29, 0xf6, 0xf4, 0x57, 0x9a, 0x61, 0xea, 0x56, 0x0f, 0x2b, 0xed, 0x52, 0xa0, 0x63,
	0x5b, 0xa6, 0x83, 0x95, 0x4d, 0xf4, 0x08, 0xfe, 0x37, 0x23, 0xf4, 0x8e, 0x2e, 0x3c, 0x9b, 0xe0,
	0x63, 0xe3, 0xad, 0xd2, 0x11, 0x5c, 0xa7, 0x18, 0xdb, 0x5a, 0xdf, 0x38, 0xc7, 0x0a, 0x42, 0x3b,
	0xf0, 0xb8, 0x88, 0xbb, 0x70, 0x5c, 0x7c, 0xe6, 0xe9, 0x96, 0x79, 0x6c, 0x9c, 0x78, 0x04, 0xbf,
	0x19, 0x60, 0xc7, 0x55, 0x1e, 0xa1, 0x6d, 0x78, 0x28, 0xdc, 0xba, 0x65, 0xba, 0x44, 0xd3, 0x5d,
	0x4f, 0xeb, 0x57, 0x32, 0xba, 0xe8, 0xff, 0x70, 0x5f, 0xf8, 0x5c, 0xeb, 0x14, 0x9b, 0xde, 0x91,
	0xd6, 0xd7, 0x4c, 0x1d, 0x2b, 0x8f, 0xd1, 0x7d, 0xd8, 0xb4, 0xb5, 0x0b, 0xcf, 0x1a, 0x48, 0x97,
	0xb2, 0x8d, 0x14, 0xd8, 0x28, 0x1b, 0x29, 0x2d, 0x5f, 0x09, 0x8b, 0x33, 0xb0, 0xed, 0xfe, 0x85,
	0xb4, 0x3c, 0x11, 0x9f, 0x15, 0x6c, 0xc6, 0x19, 0x76, 0x5c, 0xed, 0xcc, 0x56, 0x76, 0x84, 0x54,
	0x07, 0x9b, 0x3d, 0xef, 0xf5, 0x80, 0x5c, 0x28, 0x4f, 0x05, 0x24, 0x58, 0x3f, 0x2f, 0xe1, 0x33,
	0x84, 0xa0, 0x53, 0x48, 0xc3, 0xa4, 0x6a, 0xd4, 0xae, 0x20, 0xb1, 0x06, 0x6e, 0xd1, 0x15, 0x4f,
	0xd7, 0xfa, 0x7d, 0xe5, 0xb9, 0xfa, 0x0e, 0x9a, 0x27, 0x94, 0x3b, 0xdc, 0xe7, 0x14, 0x29, 0x50,
	0x7f, 0x4f, 0xa7, 0xc5, 0x56, 0x69, 0x11, 0xf1, 0x13, 0x3d, 0x05, 0x08, 0x58, 0x1c, 0xd3, 0x80,
	0x47, 0x2c, 0x29, 0xf6, 0x42, 0x8b, 0x2c, 0x58, 0x4a, 0x7f, 0x35, 0x1b, 0x72, 0xe6, 0x17, 0xa7,
	0xe5, 0x35, 0x28, 0x15, 0xfb, 0xd1, 0xd4, 0x4e, 0xe9, 0x55, 0xf4, 0x11, 0x3d, 0x84, 0xb5, 0x49,
	0xf1, 0x4b, 0x26, 0x92, 0x68, 0x89, 0x6b, 0xe5, 0x16, 0x97, 0x0d, 0x1b, 0x27, 0x94, 0xcf, 0xf6,
	0x1d, 0xda, 0x85, 0x76, 0xea, 0x27, 0x43, 0x6a, 0xe6, 0xe3, 0x4b, 0x9a, 0x16, 0x64, 0x9b, 0x64,
	0xd1, 0x74, 0x97, 0x7a, 0x35, 0x85, 0xa6, 0x9d, 0x7f, 0xb6, 0xf6, 0x07, 0xb0, 0x7a, 0xed, 0xc7,
	0x39, 0x95, 0x52, 0x4a, 0xb0, 0xc4, 0x59, 0xbf, 0xa3, 0x23, 0x8d, 0x5b, 0x55, 0xbc, 0x83, 0x66,
	0x8f, 0xc6, 0xff, 0x55, 0xbf, 0x29, 0x6c, 0xcd, 0xfb, 0x4d, 0x44, 0x2b, 0xd0, 0x36, 0x34, 0x33,
	0xee, 0xa7, 0xfc, 0x74, 0x96, 0x69, 0x86, 0xc5, 0x52, 0xd0, 0x24, 0x14, 0x9e, 0x32, 0x95, 0x44,
	0x77, 0x15, 0xa9, 0x1e, 0x43, 0xe7, 0x84, 0xf2, 0x37, 0x39, 0x4d, 0xa7, 0x84, 0x66, 0x79, 0xcc,
	0x45, 0xb3, 0x3e, 0x08, 0x28, 0x53, 0x94, 0xe0, 0xce, 0x05, 0xf8, 0xba, 0x18, 0x8f, 0x57, 0x51,
	0xc6, 0x59, 0x3a, 0x3d, 0x66, 0xa9, 0xc8, 0x7d, 0xab, 0x29, 0xea, 0x2e, 0x74, 0x8a, 0x54, 0x45,
	0x59, 0x26, 0xfd, 0xc8, 0x51, 0x07, 0x56, 0xa2, 0x50, 0x86, 0xac, 0x44, 0xa1, 0xfa, 0x1c, 0xb6,
	0xe6, 0x11, 0x7a, 0xcc, 0x32, 0x7a, 0x2b, 0xe4, 0x07, 0x50, 0x16, 0xf4, 0x1e, 0x4d, 0x39, 0xcd,
	0x8a, 0x09, 0x9a, 0xc3, 0x22, 0x78, 0x83, 0x2c, 0x9a, 0xd4, 0x04, 0x36, 0xab, 0xaf, 0x26, 0x2c,
	0xc9, 0x28, 0x3a, 0x84, 0xf5, 0xd2, 0x2f, 0xc2, 0xeb, 0x7b, 0xed, 0xc3, 0x6e, 0x75, 0xee, 0x2e,
	0xb3, 0x93, 0x2a, 0x10, 0x3d, 0x86, 0xe6, 0xc8, 0xcf, 0xbc, 0x31, 0x4b, 0xcb, 0x59, 0x6a, 0x92,
	0xf5, 0x91, 0x9f, 0x9d, 0xb1, 0xb4, 0x52, 0x59, 0x9f, 0xa9, 0xfc, 0xad, 0x06, 0x1b, 0x56, 0xce,
	0x8b, 0x33, 0x5c, 0xf7, 0xe3, 0x18, 0xa9, 0x73, 0x6c, 0xfa, 0x63, 0x2a, 0x0b, 0xba, 0x61, 0x13,
	0xab, 0x38, 0xa6, 0x7c, 0xc4, 0xc2, 0x6a, 0x15, 0x4b, 0x54, 0x6c, 0x34, 0x3f, 0xf5, 0xc7, 0x99,
	0x1c, 0x14, 0x89, 0x96, 0x56, 0xa5, 0x71, 0x6b, 0x55, 0x5e, 0x16, 0x1b, 0x4d, 0xa7, 0xe9, 0x3f,
	0x3d, 0x16, 0xd4, 0x3f, 0x6a, 0xd0, 0x74, 0x68, 0x12, 0xbe, 0xce, 0xd3, 0xa9, 0xb8, 0x14, 0xc7,
	0xd9, 0xd0, 0xad, 0x2e, 0xe1, 0x4d, 0x52, 0x41, 0xf4, 0x02, 0x3a, 0x01, 0x4b, 0x44, 0x93, 0xc4,
	0x13, 0x40, 0xdc, 0x65, 0xe5, 0x56, 0x5b, 0xb2, 0x8a, 0x11, 0x1e, 0x4f, 0xb5, 0x24, 0xfb, 0x95,
	0xa6, 0xb2, 0x94, 0x19, 0xbe, 0xb3, 0x98, 0xdf, 0x6b, 0xd0, 0x24, 0x34, 0xb8, 0xfe, 0x97, 0xa4,
	0x74, 0x61, 0x5d, 0x5c, 0xf7, 0x2c, 0xe7, 0x85, 0x92, 0x4d, 0x52, 0xc1, 0x3b, 0x85, 0x68, 0xc5,
	0xd6, 0x74, 0xd9, 0x7b, 0x9a, 0x1c, 0xf9, 0xb1, 0x9f, 0x04, 0x54, 0x90, 0xf9, 0x61, 0x98, 0xd2,
	0x2c, 0x93, 0xcd, 0xad, 0xa0, 0xd8, 0x4e, 0x7e, 0x96, 0x51, 0x2e, 0x7b, 0x5b, 0x02, 0xf5, 0x03,
	0xb4, 0x6d, 0x7f, 0x6a, 0xe5, 0x25, 0xcb, 0x3c, 0xa8, 0x1c, 0xdc, 0x12, 0x88, 0x55, 0xf7, 0xc7,
	0x2c, 0x97, 0x15, 0x34, 0x88, 0x44, 0xa2, 0x89, 0x31, 0x0b, 0xde, 0x0b, 0xb9, 0x52, 0xfa, 0x0c,
	0x2f, 0x0a, 0x69, 0xdc, 0x10, 0xa2, 0xfe, 0x02, 0xed, 0x1e, 0xbd, 0x8a, 0x12, 0x5a, 0xa6, 0x7c,
	0x02, 0x2d, 0x2e, 0x7e, 0xcc, 0x5a, 0xb8, 0x4a, 0xe6, 0x06, 0x91, 0x3a, 0x2c, 0x82, 0x65, 0xf3,
	0x24, 0x12, 0xf4, 0x41, 0x4a, 0x7d, 0xce, 0x52, 0x39, 0xea, 0x15, 0x54, 0x73, 0x68, 0x3b, 0xf9,
	0x64, 0x12, 0x4f, 0x4b, 0x7a, 0xa1, 0x43, 0x14, 0x61, 0x84, 0xb2, 0xa6, 0x0a, 0x0a, 0xf5, 0x79,
	0x12, 0x7d, 0xc8, 0xe9, 0xec, 0x6a, 0x98, 0xe1, 0x85, 0x8a, 0xeb, 0x37, 0x2a, 0x5e, 0x48, 0xdb,
	0xb8, 0x99, 0xf6, 0x05, 0xa0, 0x53, 0x2a, 0x0e, 0x1c, 0x67, 0x9a, 0x71, 0x2a, 0x1e, 0xa0, 0x57,
	0xd1, 0xf0, 0x13, 0x27, 0xcf, 0x2b, 0x40, 0xcb, 0xd7, 0xd7, 0xe9, 0xf5, 0x27, 0xf6, 0xc3, 0xd2,
	0x41, 0xb2, 0x72, 0xeb, 0x20, 0x39, 0x7c, 0xbb, 0xf0, 0x34, 0x15, 0x15, 0xb3, 0x94, 0xa3, 0x9e,
	0x98, 0xcc, 0x61, 0x94, 0x71, 0x9a, 0xa2, 0xee, 0xe7, 0x1e, 0xa6, 0xdb, 0x9f, 0xf5, 0xa8, 0xf7,
	0xf6, 0x6a, 0xdf, 0xd6, 0x8e, 0x2c, 0x68, 0xcb, 0x00, 0xf1, 0x68, 0xfe, 0xf9, 0xe5, 0x97, 0x3e,
	0xbb, 0x2f, 0xcb, 0x7f, 0x0c, 0xbe, 0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x17, 0x4a, 0x9c, 0x32,
	0x37, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeSupportClient is the client API for ChaincodeSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], "/protos.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChaincodeSupportServer is the server API for ChaincodeSupport service.
type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chaincode_shim.proto",
}
