// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode_shim.proto

package peer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED                              ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER                               ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED                             ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                                   ChaincodeMessage_Type = 3
	ChaincodeMessage_READY                                  ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION                            ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED                              ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR                                  ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE                              ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE                              ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE                              ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE                       ChaincodeMessage_Type = 11
	ChaincodeMessage_RESPONSE                               ChaincodeMessage_Type = 13
	ChaincodeMessage_GET_STATE_BY_RANGE                     ChaincodeMessage_Type = 14
	ChaincodeMessage_GET_QUERY_RESULT                       ChaincodeMessage_Type = 15
	ChaincodeMessage_QUERY_STATE_NEXT                       ChaincodeMessage_Type = 16
	ChaincodeMessage_QUERY_STATE_CLOSE                      ChaincodeMessage_Type = 17
	ChaincodeMessage_KEEPALIVE                              ChaincodeMessage_Type = 18
	ChaincodeMessage_GET_HISTORY_FOR_KEY                    ChaincodeMessage_Type = 19
	ChaincodeMessage_OUTCHAIN_ADDRESS                       ChaincodeMessage_Type = 20
	ChaincodeMessage_OUTCHAIN_TRANSACTION                   ChaincodeMessage_Type = 21
	ChaincodeMessage_OUTCHAIN_QUERY                         ChaincodeMessage_Type = 22
	ChaincodeMessage_GET_PAYTO_CONTRACT_PTN_AMOUNTS_REQUEST ChaincodeMessage_Type = 23
	ChaincodeMessage_GET_DEPOSITCONFIGS_REQUEST             ChaincodeMessage_Type = 24
	ChaincodeMessage_GET_PAYTO_CONTRACT_FROM_ADDR_REQUEST   ChaincodeMessage_Type = 25
	ChaincodeMessage_GET_CONTRACT_ALL_STATE                 ChaincodeMessage_Type = 26
	ChaincodeMessage_GET_TOKEN_BALANCE                      ChaincodeMessage_Type = 27
	ChaincodeMessage_PAY_OUT_TOKEN                          ChaincodeMessage_Type = 28
	ChaincodeMessage_GET_PAYTO_CONTRACT_TO_ADDR_REQUEST     ChaincodeMessage_Type = 29
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	13: "RESPONSE",
	14: "GET_STATE_BY_RANGE",
	15: "GET_QUERY_RESULT",
	16: "QUERY_STATE_NEXT",
	17: "QUERY_STATE_CLOSE",
	18: "KEEPALIVE",
	19: "GET_HISTORY_FOR_KEY",
	20: "OUTCHAIN_ADDRESS",
	21: "OUTCHAIN_TRANSACTION",
	22: "OUTCHAIN_QUERY",
	23: "GET_PAYTO_CONTRACT_PTN_AMOUNTS_REQUEST",
	24: "GET_DEPOSITCONFIGS_REQUEST",
	25: "GET_PAYTO_CONTRACT_FROM_ADDR_REQUEST",
	26: "GET_CONTRACT_ALL_STATE",
	27: "GET_TOKEN_BALANCE",
	28: "PAY_OUT_TOKEN",
	29: "GET_PAYTO_CONTRACT_TO_ADDR_REQUEST",
}

var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":                              0,
	"REGISTER":                               1,
	"REGISTERED":                             2,
	"INIT":                                   3,
	"READY":                                  4,
	"TRANSACTION":                            5,
	"COMPLETED":                              6,
	"ERROR":                                  7,
	"GET_STATE":                              8,
	"PUT_STATE":                              9,
	"DEL_STATE":                              10,
	"INVOKE_CHAINCODE":                       11,
	"RESPONSE":                               13,
	"GET_STATE_BY_RANGE":                     14,
	"GET_QUERY_RESULT":                       15,
	"QUERY_STATE_NEXT":                       16,
	"QUERY_STATE_CLOSE":                      17,
	"KEEPALIVE":                              18,
	"GET_HISTORY_FOR_KEY":                    19,
	"OUTCHAIN_ADDRESS":                       20,
	"OUTCHAIN_TRANSACTION":                   21,
	"OUTCHAIN_QUERY":                         22,
	"GET_PAYTO_CONTRACT_PTN_AMOUNTS_REQUEST": 23,
	"GET_DEPOSITCONFIGS_REQUEST":             24,
	"GET_PAYTO_CONTRACT_FROM_ADDR_REQUEST":   25,
	"GET_CONTRACT_ALL_STATE":                 26,
	"GET_TOKEN_BALANCE":                      27,
	"PAY_OUT_TOKEN":                          28,
	"GET_PAYTO_CONTRACT_TO_ADDR_REQUEST":     29,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}

func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{0, 0}
}

type ChaincodeMessage struct {
	Type      ChaincodeMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   []byte                `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid      string                `protobuf:"bytes,4,opt,name=txid,proto3" json:"txid,omitempty"`
	Proposal  *SignedProposal       `protobuf:"bytes,5,opt,name=proposal,proto3" json:"proposal,omitempty"`
	//event emitted by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	//with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincode_event,json=chaincodeEvent,proto3" json:"chaincode_event,omitempty"`
	//channel id
	ChannelId string `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	//contract id
	ContractId           []byte   `protobuf:"bytes,8,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeMessage) Reset()         { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()    {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{0}
}

func (m *ChaincodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeMessage.Unmarshal(m, b)
}
func (m *ChaincodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeMessage.Marshal(b, m, deterministic)
}
func (m *ChaincodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeMessage.Merge(m, src)
}
func (m *ChaincodeMessage) XXX_Size() int {
	return xxx_messageInfo_ChaincodeMessage.Size(m)
}
func (m *ChaincodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeMessage proto.InternalMessageInfo

func (m *ChaincodeMessage) GetType() ChaincodeMessage_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeMessage_UNDEFINED
}

func (m *ChaincodeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChaincodeMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChaincodeMessage) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ChaincodeMessage) GetProposal() *SignedProposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

func (m *ChaincodeMessage) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ChaincodeMessage) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

type GetState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{1}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type PutState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutState) Reset()         { *m = PutState{} }
func (m *PutState) String() string { return proto.CompactTextString(m) }
func (*PutState) ProtoMessage()    {}
func (*PutState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{2}
}

func (m *PutState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutState.Unmarshal(m, b)
}
func (m *PutState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutState.Marshal(b, m, deterministic)
}
func (m *PutState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutState.Merge(m, src)
}
func (m *PutState) XXX_Size() int {
	return xxx_messageInfo_PutState.Size(m)
}
func (m *PutState) XXX_DiscardUnknown() {
	xxx_messageInfo_PutState.DiscardUnknown(m)
}

var xxx_messageInfo_PutState proto.InternalMessageInfo

func (m *PutState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type DelState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelState) Reset()         { *m = DelState{} }
func (m *DelState) String() string { return proto.CompactTextString(m) }
func (*DelState) ProtoMessage()    {}
func (*DelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{3}
}

func (m *DelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelState.Unmarshal(m, b)
}
func (m *DelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelState.Marshal(b, m, deterministic)
}
func (m *DelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelState.Merge(m, src)
}
func (m *DelState) XXX_Size() int {
	return xxx_messageInfo_DelState.Size(m)
}
func (m *DelState) XXX_DiscardUnknown() {
	xxx_messageInfo_DelState.DiscardUnknown(m)
}

var xxx_messageInfo_DelState proto.InternalMessageInfo

func (m *DelState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DelState) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetStateByRange struct {
	StartKey             string   `protobuf:"bytes,1,opt,name=startKey,proto3" json:"startKey,omitempty"`
	EndKey               string   `protobuf:"bytes,2,opt,name=endKey,proto3" json:"endKey,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateByRange) Reset()         { *m = GetStateByRange{} }
func (m *GetStateByRange) String() string { return proto.CompactTextString(m) }
func (*GetStateByRange) ProtoMessage()    {}
func (*GetStateByRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{4}
}

func (m *GetStateByRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateByRange.Unmarshal(m, b)
}
func (m *GetStateByRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateByRange.Marshal(b, m, deterministic)
}
func (m *GetStateByRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateByRange.Merge(m, src)
}
func (m *GetStateByRange) XXX_Size() int {
	return xxx_messageInfo_GetStateByRange.Size(m)
}
func (m *GetStateByRange) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateByRange.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateByRange proto.InternalMessageInfo

func (m *GetStateByRange) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *GetStateByRange) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *GetStateByRange) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetQueryResult struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQueryResult) Reset()         { *m = GetQueryResult{} }
func (m *GetQueryResult) String() string { return proto.CompactTextString(m) }
func (*GetQueryResult) ProtoMessage()    {}
func (*GetQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{5}
}

func (m *GetQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueryResult.Unmarshal(m, b)
}
func (m *GetQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueryResult.Marshal(b, m, deterministic)
}
func (m *GetQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueryResult.Merge(m, src)
}
func (m *GetQueryResult) XXX_Size() int {
	return xxx_messageInfo_GetQueryResult.Size(m)
}
func (m *GetQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueryResult proto.InternalMessageInfo

func (m *GetQueryResult) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GetQueryResult) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetHistoryForKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryForKey) Reset()         { *m = GetHistoryForKey{} }
func (m *GetHistoryForKey) String() string { return proto.CompactTextString(m) }
func (*GetHistoryForKey) ProtoMessage()    {}
func (*GetHistoryForKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{6}
}

func (m *GetHistoryForKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryForKey.Unmarshal(m, b)
}
func (m *GetHistoryForKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryForKey.Marshal(b, m, deterministic)
}
func (m *GetHistoryForKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryForKey.Merge(m, src)
}
func (m *GetHistoryForKey) XXX_Size() int {
	return xxx_messageInfo_GetHistoryForKey.Size(m)
}
func (m *GetHistoryForKey) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryForKey.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryForKey proto.InternalMessageInfo

func (m *GetHistoryForKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type QueryStateNext struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStateNext) Reset()         { *m = QueryStateNext{} }
func (m *QueryStateNext) String() string { return proto.CompactTextString(m) }
func (*QueryStateNext) ProtoMessage()    {}
func (*QueryStateNext) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{7}
}

func (m *QueryStateNext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStateNext.Unmarshal(m, b)
}
func (m *QueryStateNext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStateNext.Marshal(b, m, deterministic)
}
func (m *QueryStateNext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStateNext.Merge(m, src)
}
func (m *QueryStateNext) XXX_Size() int {
	return xxx_messageInfo_QueryStateNext.Size(m)
}
func (m *QueryStateNext) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStateNext.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStateNext proto.InternalMessageInfo

func (m *QueryStateNext) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryStateClose struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStateClose) Reset()         { *m = QueryStateClose{} }
func (m *QueryStateClose) String() string { return proto.CompactTextString(m) }
func (*QueryStateClose) ProtoMessage()    {}
func (*QueryStateClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{8}
}

func (m *QueryStateClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStateClose.Unmarshal(m, b)
}
func (m *QueryStateClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStateClose.Marshal(b, m, deterministic)
}
func (m *QueryStateClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStateClose.Merge(m, src)
}
func (m *QueryStateClose) XXX_Size() int {
	return xxx_messageInfo_QueryStateClose.Size(m)
}
func (m *QueryStateClose) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStateClose.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStateClose proto.InternalMessageInfo

func (m *QueryStateClose) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryResultBytes struct {
	ResultBytes          []byte   `protobuf:"bytes,1,opt,name=resultBytes,proto3" json:"resultBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResultBytes) Reset()         { *m = QueryResultBytes{} }
func (m *QueryResultBytes) String() string { return proto.CompactTextString(m) }
func (*QueryResultBytes) ProtoMessage()    {}
func (*QueryResultBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{9}
}

func (m *QueryResultBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultBytes.Unmarshal(m, b)
}
func (m *QueryResultBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultBytes.Marshal(b, m, deterministic)
}
func (m *QueryResultBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultBytes.Merge(m, src)
}
func (m *QueryResultBytes) XXX_Size() int {
	return xxx_messageInfo_QueryResultBytes.Size(m)
}
func (m *QueryResultBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultBytes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultBytes proto.InternalMessageInfo

func (m *QueryResultBytes) GetResultBytes() []byte {
	if m != nil {
		return m.ResultBytes
	}
	return nil
}

type QueryResponse struct {
	Results              []*QueryResultBytes `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore              bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Id                   string              `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{10}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*QueryResultBytes {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *QueryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type OutChainAddress struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainAddress) Reset()         { *m = OutChainAddress{} }
func (m *OutChainAddress) String() string { return proto.CompactTextString(m) }
func (*OutChainAddress) ProtoMessage()    {}
func (*OutChainAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{11}
}

func (m *OutChainAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainAddress.Unmarshal(m, b)
}
func (m *OutChainAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainAddress.Marshal(b, m, deterministic)
}
func (m *OutChainAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainAddress.Merge(m, src)
}
func (m *OutChainAddress) XXX_Size() int {
	return xxx_messageInfo_OutChainAddress.Size(m)
}
func (m *OutChainAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainAddress.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainAddress proto.InternalMessageInfo

func (m *OutChainAddress) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainAddress) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainAddress) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type OutChainTransaction struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainTransaction) Reset()         { *m = OutChainTransaction{} }
func (m *OutChainTransaction) String() string { return proto.CompactTextString(m) }
func (*OutChainTransaction) ProtoMessage()    {}
func (*OutChainTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{12}
}

func (m *OutChainTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainTransaction.Unmarshal(m, b)
}
func (m *OutChainTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainTransaction.Marshal(b, m, deterministic)
}
func (m *OutChainTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainTransaction.Merge(m, src)
}
func (m *OutChainTransaction) XXX_Size() int {
	return xxx_messageInfo_OutChainTransaction.Size(m)
}
func (m *OutChainTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainTransaction proto.InternalMessageInfo

func (m *OutChainTransaction) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainTransaction) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainTransaction) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type OutChainQuery struct {
	OutChainName         string   `protobuf:"bytes,1,opt,name=OutChainName,proto3" json:"OutChainName,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Collection           string   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutChainQuery) Reset()         { *m = OutChainQuery{} }
func (m *OutChainQuery) String() string { return proto.CompactTextString(m) }
func (*OutChainQuery) ProtoMessage()    {}
func (*OutChainQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{13}
}

func (m *OutChainQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutChainQuery.Unmarshal(m, b)
}
func (m *OutChainQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutChainQuery.Marshal(b, m, deterministic)
}
func (m *OutChainQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutChainQuery.Merge(m, src)
}
func (m *OutChainQuery) XXX_Size() int {
	return xxx_messageInfo_OutChainQuery.Size(m)
}
func (m *OutChainQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_OutChainQuery.DiscardUnknown(m)
}

var xxx_messageInfo_OutChainQuery proto.InternalMessageInfo

func (m *OutChainQuery) GetOutChainName() string {
	if m != nil {
		return m.OutChainName
	}
	return ""
}

func (m *OutChainQuery) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *OutChainQuery) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetTokenBalance struct {
	Asset                []byte   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenBalance) Reset()         { *m = GetTokenBalance{} }
func (m *GetTokenBalance) String() string { return proto.CompactTextString(m) }
func (*GetTokenBalance) ProtoMessage()    {}
func (*GetTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{14}
}

func (m *GetTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenBalance.Unmarshal(m, b)
}
func (m *GetTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenBalance.Marshal(b, m, deterministic)
}
func (m *GetTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenBalance.Merge(m, src)
}
func (m *GetTokenBalance) XXX_Size() int {
	return xxx_messageInfo_GetTokenBalance.Size(m)
}
func (m *GetTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenBalance proto.InternalMessageInfo

func (m *GetTokenBalance) GetAsset() []byte {
	if m != nil {
		return m.Asset
	}
	return nil
}

type PayOutToken struct {
	Asset                []byte   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Locktime             uint32   `protobuf:"varint,3,opt,name=locktime,proto3" json:"locktime,omitempty"`
	Collection           string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutToken) Reset()         { *m = PayOutToken{} }
func (m *PayOutToken) String() string { return proto.CompactTextString(m) }
func (*PayOutToken) ProtoMessage()    {}
func (*PayOutToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{15}
}

func (m *PayOutToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutToken.Unmarshal(m, b)
}
func (m *PayOutToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutToken.Marshal(b, m, deterministic)
}
func (m *PayOutToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutToken.Merge(m, src)
}
func (m *PayOutToken) XXX_Size() int {
	return xxx_messageInfo_PayOutToken.Size(m)
}
func (m *PayOutToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutToken.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutToken proto.InternalMessageInfo

func (m *PayOutToken) GetAsset() []byte {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *PayOutToken) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayOutToken) GetLocktime() uint32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *PayOutToken) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type DepositCfg struct {
	DepositAmount        uint64   `protobuf:"varint,1,opt,name=DepositAmount,proto3" json:"DepositAmount,omitempty"`
	DepositRate          float64  `protobuf:"fixed64,2,opt,name=DepositRate,proto3" json:"DepositRate,omitempty"`
	FoundationAddress    []byte   `protobuf:"bytes,3,opt,name=FoundationAddress,proto3" json:"FoundationAddress,omitempty"`
	Collection           string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositCfg) Reset()         { *m = DepositCfg{} }
func (m *DepositCfg) String() string { return proto.CompactTextString(m) }
func (*DepositCfg) ProtoMessage()    {}
func (*DepositCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{16}
}

func (m *DepositCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositCfg.Unmarshal(m, b)
}
func (m *DepositCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositCfg.Marshal(b, m, deterministic)
}
func (m *DepositCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositCfg.Merge(m, src)
}
func (m *DepositCfg) XXX_Size() int {
	return xxx_messageInfo_DepositCfg.Size(m)
}
func (m *DepositCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositCfg.DiscardUnknown(m)
}

var xxx_messageInfo_DepositCfg proto.InternalMessageInfo

func (m *DepositCfg) GetDepositAmount() uint64 {
	if m != nil {
		return m.DepositAmount
	}
	return 0
}

func (m *DepositCfg) GetDepositRate() float64 {
	if m != nil {
		return m.DepositRate
	}
	return 0
}

func (m *DepositCfg) GetFoundationAddress() []byte {
	if m != nil {
		return m.FoundationAddress
	}
	return nil
}

func (m *DepositCfg) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type PayToContractFromAddr struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayToContractFromAddr) Reset()         { *m = PayToContractFromAddr{} }
func (m *PayToContractFromAddr) String() string { return proto.CompactTextString(m) }
func (*PayToContractFromAddr) ProtoMessage()    {}
func (*PayToContractFromAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{17}
}

func (m *PayToContractFromAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayToContractFromAddr.Unmarshal(m, b)
}
func (m *PayToContractFromAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayToContractFromAddr.Marshal(b, m, deterministic)
}
func (m *PayToContractFromAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayToContractFromAddr.Merge(m, src)
}
func (m *PayToContractFromAddr) XXX_Size() int {
	return xxx_messageInfo_PayToContractFromAddr.Size(m)
}
func (m *PayToContractFromAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_PayToContractFromAddr.DiscardUnknown(m)
}

var xxx_messageInfo_PayToContractFromAddr proto.InternalMessageInfo

func (m *PayToContractFromAddr) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type PayToContractPtnAmount struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayToContractPtnAmount) Reset()         { *m = PayToContractPtnAmount{} }
func (m *PayToContractPtnAmount) String() string { return proto.CompactTextString(m) }
func (*PayToContractPtnAmount) ProtoMessage()    {}
func (*PayToContractPtnAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{18}
}

func (m *PayToContractPtnAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayToContractPtnAmount.Unmarshal(m, b)
}
func (m *PayToContractPtnAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayToContractPtnAmount.Marshal(b, m, deterministic)
}
func (m *PayToContractPtnAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayToContractPtnAmount.Merge(m, src)
}
func (m *PayToContractPtnAmount) XXX_Size() int {
	return xxx_messageInfo_PayToContractPtnAmount.Size(m)
}
func (m *PayToContractPtnAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_PayToContractPtnAmount.DiscardUnknown(m)
}

var xxx_messageInfo_PayToContractPtnAmount proto.InternalMessageInfo

func (m *PayToContractPtnAmount) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PayToContractToAddr struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayToContractToAddr) Reset()         { *m = PayToContractToAddr{} }
func (m *PayToContractToAddr) String() string { return proto.CompactTextString(m) }
func (*PayToContractToAddr) ProtoMessage()    {}
func (*PayToContractToAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb8e00c9c92d6c8, []int{19}
}

func (m *PayToContractToAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayToContractToAddr.Unmarshal(m, b)
}
func (m *PayToContractToAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayToContractToAddr.Marshal(b, m, deterministic)
}
func (m *PayToContractToAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayToContractToAddr.Merge(m, src)
}
func (m *PayToContractToAddr) XXX_Size() int {
	return xxx_messageInfo_PayToContractToAddr.Size(m)
}
func (m *PayToContractToAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_PayToContractToAddr.DiscardUnknown(m)
}

var xxx_messageInfo_PayToContractToAddr proto.InternalMessageInfo

func (m *PayToContractToAddr) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
	proto.RegisterType((*ChaincodeMessage)(nil), "protos.ChaincodeMessage")
	proto.RegisterType((*GetState)(nil), "protos.GetState")
	proto.RegisterType((*PutState)(nil), "protos.PutState")
	proto.RegisterType((*DelState)(nil), "protos.DelState")
	proto.RegisterType((*GetStateByRange)(nil), "protos.GetStateByRange")
	proto.RegisterType((*GetQueryResult)(nil), "protos.GetQueryResult")
	proto.RegisterType((*GetHistoryForKey)(nil), "protos.GetHistoryForKey")
	proto.RegisterType((*QueryStateNext)(nil), "protos.QueryStateNext")
	proto.RegisterType((*QueryStateClose)(nil), "protos.QueryStateClose")
	proto.RegisterType((*QueryResultBytes)(nil), "protos.QueryResultBytes")
	proto.RegisterType((*QueryResponse)(nil), "protos.QueryResponse")
	proto.RegisterType((*OutChainAddress)(nil), "protos.OutChainAddress")
	proto.RegisterType((*OutChainTransaction)(nil), "protos.OutChainTransaction")
	proto.RegisterType((*OutChainQuery)(nil), "protos.OutChainQuery")
	proto.RegisterType((*GetTokenBalance)(nil), "protos.GetTokenBalance")
	proto.RegisterType((*PayOutToken)(nil), "protos.PayOutToken")
	proto.RegisterType((*DepositCfg)(nil), "protos.DepositCfg")
	proto.RegisterType((*PayToContractFromAddr)(nil), "protos.PayToContractFromAddr")
	proto.RegisterType((*PayToContractPtnAmount)(nil), "protos.PayToContractPtnAmount")
	proto.RegisterType((*PayToContractToAddr)(nil), "protos.PayToContractToAddr")
}

func init() { proto.RegisterFile("chaincode_shim.proto", fileDescriptor_adb8e00c9c92d6c8) }

var fileDescriptor_adb8e00c9c92d6c8 = []byte{
	// 1222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x52, 0xdb, 0x46,
	0x14, 0x8e, 0xc1, 0x80, 0x7d, 0x0c, 0x66, 0x59, 0x08, 0x71, 0xdc, 0x26, 0xa1, 0x9e, 0x4c, 0xca,
	0x74, 0x5a, 0x9c, 0xd0, 0x5e, 0xf4, 0x22, 0x33, 0xad, 0xb0, 0xd7, 0x8e, 0x07, 0x23, 0x29, 0xab,
	0x75, 0x26, 0xee, 0x8d, 0x66, 0xb1, 0x37, 0xc6, 0x83, 0xac, 0x55, 0xa4, 0x75, 0x1a, 0xbf, 0x4e,
	0x9f, 0xa9, 0xef, 0xd1, 0x57, 0xe8, 0xac, 0x7e, 0xfc, 0x03, 0x49, 0x99, 0x69, 0x26, 0x57, 0xf8,
	0x3b, 0xe7, 0x3b, 0xdf, 0xf9, 0xf6, 0x68, 0x25, 0x0e, 0x1c, 0x0c, 0xae, 0xf8, 0xd8, 0x1f, 0xc8,
	0xa1, 0x70, 0xa3, 0xab, 0xf1, 0xe4, 0x24, 0x08, 0xa5, 0x92, 0x78, 0x33, 0xfe, 0x13, 0x55, 0xdf,
	0x8c, 0xc6, 0xea, 0x6a, 0x7a, 0x79, 0x32, 0x90, 0x93, 0x7a, 0xc0, 0x3d, 0x4f, 0x28, 0xe9, 0x8b,
	0xfa, 0x48, 0xfe, 0xb4, 0x00, 0x03, 0x19, 0x8a, 0xfa, 0x87, 0x49, 0x43, 0xfa, 0x2a, 0xe4, 0x03,
	0x65, 0x4f, 0x2f, 0xeb, 0x49, 0x71, 0x3d, 0x10, 0x22, 0xac, 0x2f, 0xe4, 0xc5, 0x07, 0xe1, 0xab,
	0x44, 0xbf, 0x6a, 0x7d, 0xb1, 0x6e, 0x10, 0xca, 0x40, 0x46, 0xdc, 0x4b, 0x05, 0x9f, 0x8c, 0xa4,
	0x1c, 0x79, 0x22, 0xa1, 0x5c, 0x4e, 0xdf, 0xd5, 0xd5, 0x78, 0x22, 0x22, 0xc5, 0x27, 0x41, 0x42,
	0xa8, 0xfd, 0xbd, 0x05, 0xa8, 0x91, 0x79, 0xb9, 0x10, 0x51, 0xc4, 0x47, 0x02, 0xbf, 0x80, 0xbc,
	0x9a, 0x05, 0xa2, 0x92, 0x3b, 0xca, 0x1d, 0x97, 0x4f, 0x1f, 0x25, 0xd4, 0xe8, 0xe4, 0x26, 0xef,
	0x84, 0xcd, 0x02, 0x41, 0x63, 0x2a, 0xfe, 0x15, 0x8a, 0x73, 0xe9, 0xca, 0xda, 0x51, 0xee, 0xb8,
	0x74, 0x5a, 0x3d, 0x49, 0x9a, 0x9f, 0x64, 0xcd, 0x4f, 0x58, 0xc6, 0xa0, 0x0b, 0x32, 0xae, 0xc0,
	0x56, 0xc0, 0x67, 0x9e, 0xe4, 0xc3, 0xca, 0xfa, 0x51, 0xee, 0x78, 0x9b, 0x66, 0x10, 0x63, 0xc8,
	0xab, 0x8f, 0xe3, 0x61, 0x25, 0x7f, 0x94, 0x3b, 0x2e, 0xd2, 0xf8, 0x37, 0x3e, 0x85, 0x42, 0x76,
	0xc4, 0xca, 0x46, 0xdc, 0xe6, 0x30, 0xb3, 0xe7, 0x8c, 0x47, 0xbe, 0x18, 0xda, 0x69, 0x96, 0xce,
	0x79, 0xf8, 0x37, 0xd8, 0xbd, 0x31, 0xee, 0xca, 0xe6, 0x6a, 0xe9, 0xfc, 0x64, 0x44, 0x67, 0x69,
	0x79, 0xb0, 0x82, 0xf1, 0x23, 0x80, 0xc1, 0x15, 0xf7, 0x7d, 0xe1, 0xb9, 0xe3, 0x61, 0x65, 0x2b,
	0xb6, 0x53, 0x4c, 0x23, 0x9d, 0x21, 0x7e, 0x02, 0xa5, 0x41, 0xfa, 0x38, 0x74, 0xbe, 0x10, 0x9f,
	0x02, 0xb2, 0x50, 0x67, 0x58, 0xfb, 0x27, 0x0f, 0x79, 0x3d, 0x2b, 0xbc, 0x03, 0xc5, 0x9e, 0xd9,
	0x24, 0xad, 0x8e, 0x49, 0x9a, 0xe8, 0x1e, 0xde, 0x86, 0x02, 0x25, 0xed, 0x8e, 0xc3, 0x08, 0x45,
	0x39, 0x5c, 0x06, 0xc8, 0x10, 0x69, 0xa2, 0x35, 0x5c, 0x80, 0x7c, 0xc7, 0xec, 0x30, 0xb4, 0x8e,
	0x8b, 0xb0, 0x41, 0x89, 0xd1, 0xec, 0xa3, 0x3c, 0xde, 0x85, 0x12, 0xa3, 0x86, 0xe9, 0x18, 0x0d,
	0xd6, 0xb1, 0x4c, 0xb4, 0xa1, 0x25, 0x1b, 0xd6, 0x85, 0xdd, 0x25, 0x8c, 0x34, 0xd1, 0xa6, 0xa6,
	0x12, 0x4a, 0x2d, 0x8a, 0xb6, 0x74, 0xa6, 0x4d, 0x98, 0xeb, 0x30, 0x83, 0x11, 0x54, 0xd0, 0xd0,
	0xee, 0x65, 0xb0, 0xa8, 0x61, 0x93, 0x74, 0x53, 0x08, 0xf8, 0x00, 0x50, 0xc7, 0x7c, 0x63, 0x9d,
	0x13, 0xb7, 0xf1, 0xca, 0xe8, 0x98, 0x0d, 0xab, 0x49, 0x50, 0x29, 0x31, 0xe8, 0xd8, 0x96, 0xe9,
	0x10, 0xb4, 0x83, 0x0f, 0x01, 0xcf, 0x05, 0xdd, 0xb3, 0xbe, 0x4b, 0x0d, 0xb3, 0x4d, 0x50, 0x59,
	0xd7, 0xea, 0xf8, 0xeb, 0x1e, 0xa1, 0x7d, 0x97, 0x12, 0xa7, 0xd7, 0x65, 0x68, 0x57, 0x47, 0x93,
	0x48, 0xc2, 0x37, 0xc9, 0x5b, 0x86, 0x10, 0xbe, 0x0f, 0x7b, 0xcb, 0xd1, 0x46, 0xd7, 0x72, 0x08,
	0xda, 0xd3, 0x6e, 0xce, 0x09, 0xb1, 0x8d, 0x6e, 0xe7, 0x0d, 0x41, 0x18, 0x3f, 0x80, 0x7d, 0xad,
	0xf8, 0xaa, 0xe3, 0x30, 0x8b, 0xf6, 0xdd, 0x96, 0x45, 0xdd, 0x73, 0xd2, 0x47, 0xfb, 0x5a, 0xd4,
	0xea, 0xb1, 0xd8, 0xa2, 0x6b, 0x34, 0x9b, 0x94, 0x38, 0x0e, 0x3a, 0xc0, 0x15, 0x38, 0x98, 0x47,
	0x97, 0xa7, 0x73, 0x1f, 0x63, 0x28, 0xcf, 0x33, 0x71, 0x5f, 0x74, 0x88, 0x7f, 0x80, 0x67, 0x5a,
	0xdc, 0x36, 0xfa, 0xcc, 0x72, 0x1b, 0x96, 0xc9, 0xa8, 0xd1, 0x60, 0xae, 0xcd, 0x4c, 0xd7, 0xb8,
	0xb0, 0x7a, 0x26, 0x73, 0x5c, 0x4a, 0x5e, 0xf7, 0x88, 0xc3, 0xd0, 0x03, 0xfc, 0x18, 0xaa, 0x9a,
	0xdb, 0x24, 0xb6, 0xe5, 0x74, 0x58, 0xc3, 0x32, 0x5b, 0x9d, 0xf6, 0x22, 0x5f, 0xc1, 0xc7, 0xf0,
	0xf4, 0x13, 0x5a, 0x2d, 0x6a, 0x5d, 0xc4, 0xf6, 0xe6, 0xcc, 0x87, 0xb8, 0x0a, 0x87, 0x9a, 0x39,
	0xe7, 0x18, 0xdd, 0x6c, 0xf8, 0x55, 0x3d, 0x14, 0x9d, 0x63, 0xd6, 0x39, 0x31, 0xdd, 0x33, 0xa3,
	0x6b, 0x98, 0x0d, 0x82, 0xbe, 0xc1, 0x7b, 0xb0, 0x63, 0x1b, 0x7d, 0xd7, 0xea, 0xa5, 0x29, 0xf4,
	0x2d, 0x7e, 0x06, 0xb5, 0x4f, 0xf4, 0x63, 0xd6, 0x6a, 0xb7, 0x47, 0xb5, 0x97, 0x50, 0x68, 0x0b,
	0xe5, 0x28, 0xae, 0x04, 0x46, 0xb0, 0x7e, 0x2d, 0x66, 0xf1, 0xcb, 0x5c, 0xa4, 0xfa, 0x27, 0x7e,
	0x0c, 0x30, 0x90, 0x9e, 0x27, 0x06, 0x6a, 0x2c, 0xfd, 0xf8, 0x6d, 0x2d, 0xd2, 0xa5, 0x48, 0x8d,
	0x42, 0xc1, 0x9e, 0x7e, 0xb6, 0xfa, 0x00, 0x36, 0x3e, 0x70, 0x6f, 0x2a, 0xe2, 0xc2, 0x6d, 0x9a,
	0x80, 0x1b, 0x9a, 0xeb, 0xb7, 0x34, 0x5f, 0x42, 0xa1, 0x29, 0xbc, 0xff, 0xeb, 0x48, 0xc0, 0x6e,
	0x76, 0x9e, 0xb3, 0x19, 0xe5, 0xfe, 0x48, 0xe0, 0x2a, 0x14, 0x22, 0xc5, 0x43, 0x75, 0x3e, 0x57,
	0x9a, 0x63, 0x7c, 0x08, 0x9b, 0xc2, 0x1f, 0xea, 0x4c, 0x22, 0x95, 0xa2, 0x3b, 0x4d, 0xb6, 0xa0,
	0xdc, 0x16, 0xea, 0xf5, 0x54, 0x84, 0x33, 0x2a, 0xa2, 0xa9, 0xa7, 0xf4, 0x61, 0xdf, 0x6b, 0x98,
	0xb6, 0x48, 0xc0, 0x9d, 0x76, 0x9f, 0x02, 0x6a, 0x0b, 0xf5, 0x6a, 0x1c, 0x29, 0x19, 0xce, 0x5a,
	0x32, 0xd4, 0xbd, 0x6f, 0x1d, 0xba, 0x76, 0x04, 0xe5, 0xb8, 0x55, 0x7c, 0x2c, 0x53, 0x7c, 0x54,
	0xb8, 0x0c, 0x6b, 0xe3, 0x61, 0x4a, 0x59, 0x1b, 0x0f, 0x6b, 0xdf, 0xc1, 0xee, 0x82, 0xd1, 0xf0,
	0x64, 0x24, 0x6e, 0x51, 0x7e, 0x01, 0xb4, 0xe4, 0xf7, 0x6c, 0xa6, 0x44, 0x84, 0x8f, 0xa0, 0x14,
	0x2e, 0x60, 0x4c, 0xde, 0xa6, 0xcb, 0xa1, 0x9a, 0x0f, 0x3b, 0x59, 0x55, 0x20, 0xfd, 0x48, 0xe0,
	0x53, 0xd8, 0x4a, 0xf2, 0x9a, 0xbe, 0x7e, 0x5c, 0x3a, 0xad, 0x64, 0xdf, 0xc6, 0x9b, 0xea, 0x34,
	0x23, 0xe2, 0x87, 0x50, 0xb8, 0xe2, 0x91, 0x3b, 0x91, 0x61, 0x72, 0x17, 0x0a, 0x74, 0xeb, 0x8a,
	0x47, 0x17, 0x32, 0xcc, 0x5c, 0xae, 0xcf, 0x5d, 0x4e, 0x60, 0xd7, 0x9a, 0xaa, 0xf8, 0x33, 0x6b,
	0x0c, 0x87, 0xa1, 0x88, 0x22, 0x5c, 0x83, 0xed, 0x2c, 0x64, 0xf2, 0x89, 0x48, 0x8f, 0xb4, 0x12,
	0xd3, 0xcf, 0x31, 0xe0, 0x21, 0x9f, 0x44, 0xe9, 0x5d, 0x4b, 0xd1, 0x9d, 0xcf, 0xf1, 0x3d, 0xec,
	0x67, 0x3a, 0x2c, 0xe4, 0x7e, 0xc4, 0xe3, 0xf0, 0x57, 0x6d, 0x79, 0x0d, 0x3b, 0x99, 0x4e, 0x3c,
	0xb1, 0xaf, 0xda, 0xec, 0xfb, 0xf8, 0x75, 0x60, 0xf2, 0x5a, 0xf8, 0x67, 0xdc, 0xe3, 0xfe, 0x40,
	0xe8, 0x8b, 0xca, 0xa3, 0x48, 0xa8, 0xf4, 0x69, 0x27, 0xa0, 0xf6, 0x27, 0x94, 0x6c, 0x3e, 0xb3,
	0xa6, 0x09, 0xf7, 0xd3, 0x24, 0xed, 0x82, 0x4f, 0xe4, 0xd4, 0x57, 0xb1, 0x8b, 0x3c, 0x4d, 0x91,
	0x7e, 0xc3, 0x3c, 0x39, 0xb8, 0xd6, 0xff, 0xaa, 0x63, 0x0f, 0x3b, 0x74, 0x8e, 0x6f, 0x38, 0xcc,
	0xdf, 0x72, 0xf8, 0x57, 0x0e, 0xa0, 0x29, 0x02, 0x19, 0x8d, 0x55, 0xe3, 0xdd, 0x08, 0x3f, 0x85,
	0x9d, 0x14, 0x19, 0x49, 0xa7, 0x5c, 0xdc, 0x69, 0x35, 0xa8, 0xef, 0x6d, 0x1a, 0xa0, 0x5c, 0x25,
	0x77, 0x2a, 0x47, 0x97, 0x43, 0xf8, 0x47, 0xd8, 0x6b, 0xc9, 0xa9, 0x3f, 0xe4, 0xba, 0x49, 0x7a,
	0x93, 0xd2, 0xb5, 0xe1, 0x76, 0xe2, 0x4e, 0x93, 0x2f, 0xe0, 0xbe, 0xcd, 0x67, 0x4c, 0x66, 0xcb,
	0x54, 0x2b, 0x94, 0x13, 0x5d, 0xab, 0x77, 0x12, 0x9e, 0x8a, 0x27, 0x93, 0xca, 0x60, 0xed, 0x39,
	0x1c, 0xae, 0x94, 0xd8, 0xca, 0x4f, 0xcd, 0x2f, 0xa6, 0x98, 0x5b, 0x9e, 0x62, 0xad, 0x0e, 0xfb,
	0x2b, 0x15, 0x4c, 0xfe, 0x77, 0x8b, 0xd3, 0xb7, 0x4b, 0x1b, 0x99, 0x33, 0x0d, 0x02, 0x19, 0x2a,
	0xdc, 0x84, 0x02, 0x15, 0xa3, 0x71, 0xa4, 0x44, 0x88, 0x2b, 0x9f, 0xdb, 0xc7, 0xaa, 0x9f, 0xcd,
	0xd4, 0xee, 0x1d, 0xe7, 0x9e, 0xe7, 0xce, 0x2c, 0x28, 0xa5, 0x04, 0xbd, 0x2b, 0xfe, 0xf1, 0xfb,
	0x97, 0x6e, 0x9b, 0x97, 0xc9, 0x3e, 0xfc, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x9f,
	0x64, 0xe2, 0x2e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeSupportClient is the client API for ChaincodeSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], "/protos.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChaincodeSupportServer is the server API for ChaincodeSupport service.
type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chaincode_shim.proto",
}
